// Package expedition runs the 赛车探险队 (racing expedition, the My Room
// menu's 探险队): each week (Thursday 06:00 Beijing) an account gets ten
// missions; a crew of up to three character + kart pairs and a friend goes
// on one for the mission's hours, and comes back with exp or lucci and the
// mission's reward box. 探险币 shorten, swap and add missions.
//
// expedition.json is generated by rewrite/tools/export-expedition-data.mjs
// from the CN client's zeta_/cn/content/racingExpedition/racingExpeditionMission.xml
// and stock.kml; it is embedded here and must never be edited by hand (the
// tests recompute its version).
//
// The original server decided each character's and kart's attribute (都市,
// 世界 …) and how the bonus constants combine; neither is in the client
// data. This server gives every item a fixed attribute from its id
// (Specific) and combines the original tables as documented on Bonus.
package expedition

import (
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"hash/fnv"
	"sort"
	"strconv"
	"sync"
	"time"
)

//go:embed expedition.json
var embedded []byte

// Specifics is how many attributes there are (specificType 0-7: 都市 世界 大地
// 森林 海洋 传说 神秘 特殊).
const Specifics = 8

// Mission reward kinds (mission bonusType).
const (
	RewardExp      = 0
	RewardLucci    = 1
	RewardExpLucci = 2
)

// Basic is the weekly rule set (basicInfo).
type Basic struct {
	ResetWeekday        int `json:"resetWeekday"` // 0 Sunday … 4 Thursday
	ResetHour           int `json:"resetHour"`    // Beijing hour
	FriendResetHour     int `json:"friendResetHour"`
	WeeklyMissions      int `json:"weeklyMissions"`
	BuyableMissions     int `json:"buyableMissions"`
	AddMissionTokens    int `json:"addMissionTokens"`
	ReduceTimeTokens    int `json:"reduceTimeTokens"`
	ReduceMinutes       int `json:"reduceMinutes"`
	ChangeMissionTokens int `json:"changeMissionTokens"`
	Token               struct {
		Category int `json:"category"`
		Item     int `json:"item"`
	} `json:"token"`
}

// Constants are basicBonusConst in thousandths.
type Constants struct {
	Rp                 int `json:"rp"`
	Lucci              int `json:"lucci"`
	RpLucci            int `json:"rpLucci"`
	KartBody           int `json:"kartBody"`
	Character          int `json:"character"`
	CharacterUnmatched int `json:"characterUnmatched"`
	CharacterMatched   int `json:"characterMatched"`
}

// Mission is one row of missionList.
type Mission struct {
	ID         int    `json:"id"`
	Specific   int    `json:"specific"`
	TrackID    string `json:"trackId"`
	Theme      int    `json:"theme"`
	BonusType  int    `json:"bonusType"`
	StockID    int    `json:"stockId"`
	Difficulty int    `json:"difficulty"`
	Hours      int    `json:"hours"`
}

// StockItem is one item of a reward stock.
type StockItem struct {
	Category int `json:"category"`
	ItemID   int `json:"itemId"`
	Count    int `json:"count"`
	Days     int `json:"days"`
}

// Stock is a mission's reward stock.
type Stock struct {
	Name  string      `json:"name"`
	Items []StockItem `json:"items"`
}

// Data is the embedded table.
type Data struct {
	Version   string
	Basic     Basic
	Constants Constants
	// Rewards is the base reward by difficulty 1-5.
	Rewards map[int]int
	// SpecificBonus is specificList: attribute -> bonusType.
	SpecificBonus map[int]int
	// KartTuning and Parts are bonus rows (tenths of a percent) by kart
	// tuning level and by the total of the four reinforced parts' levels,
	// one value per difficulty 1-5.
	KartTuning map[int][5]int
	Parts      map[int][5]int
	Missions   []Mission
	Stocks     map[int]Stock
	byID       map[int]*Mission
}

// Parse reads an expedition.json document.
func Parse(raw []byte) (*Data, error) {
	var doc struct {
		Version     string           `json:"version"`
		Basic       Basic            `json:"basic"`
		Bonus       Constants        `json:"bonus"`
		Rewards     map[string]int   `json:"rewards"`
		Specifics   map[string]int   `json:"specifics"`
		KartTuning  map[string][]int `json:"kartTuning"`
		Parts       map[string][]int `json:"parts"`
		Missions    []Mission        `json:"missions"`
		RewardStock map[string]Stock `json:"rewardStocks"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("expedition.json: %w", err)
	}
	if doc.Version == "" || len(doc.Missions) == 0 || doc.Basic.WeeklyMissions <= 0 {
		return nil, errors.New("expedition.json: missing version, missions or rules")
	}
	d := &Data{Version: doc.Version, Basic: doc.Basic, Constants: doc.Bonus, Rewards: map[int]int{},
		SpecificBonus: map[int]int{}, KartTuning: map[int][5]int{}, Parts: map[int][5]int{},
		Missions: doc.Missions, Stocks: map[int]Stock{}, byID: map[int]*Mission{}}
	keys := func(name string, in map[string]int, out map[int]int) error {
		for key, value := range in {
			n, err := strconv.Atoi(key)
			if err != nil {
				return fmt.Errorf("expedition.json: %s key %q", name, key)
			}
			out[n] = value
		}
		return nil
	}
	if err := keys("rewards", doc.Rewards, d.Rewards); err != nil {
		return nil, err
	}
	if err := keys("specifics", doc.Specifics, d.SpecificBonus); err != nil {
		return nil, err
	}
	rows := func(name string, in map[string][]int, out map[int][5]int) error {
		for key, values := range in {
			n, err := strconv.Atoi(key)
			if err != nil || len(values) != 5 {
				return fmt.Errorf("expedition.json: %s row %q", name, key)
			}
			out[n] = [5]int(values)
		}
		return nil
	}
	if err := rows("kartTuning", doc.KartTuning, d.KartTuning); err != nil {
		return nil, err
	}
	if err := rows("parts", doc.Parts, d.Parts); err != nil {
		return nil, err
	}
	for key, stock := range doc.RewardStock {
		id, err := strconv.Atoi(key)
		if err != nil || len(stock.Items) == 0 {
			return nil, fmt.Errorf("expedition.json: reward stock %q", key)
		}
		d.Stocks[id] = stock
	}
	for i := range d.Missions {
		m := &d.Missions[i]
		if d.byID[m.ID] != nil || d.Rewards[m.Difficulty] == 0 || m.Hours <= 0 ||
			m.Specific < 0 || m.Specific >= Specifics || len(d.Stocks[m.StockID].Items) == 0 {
			return nil, fmt.Errorf("expedition.json: bad mission %d", m.ID)
		}
		d.byID[m.ID] = m
	}
	return d, nil
}

var loadDefault = sync.OnceValues(func() (*Data, error) { return Parse(embedded) })

// Default returns the embedded table.
func Default() (*Data, error) { return loadDefault() }

// Mission returns a mission by id.
func (d *Data) Mission(id int) (*Mission, bool) {
	m, ok := d.byID[id]
	return m, ok
}

// Specific is an item's expedition attribute (0-7), fixed by its category
// and id since the client data does not carry the original server's.
func Specific(category, itemID int) int {
	h := fnv.New32a()
	_, _ = h.Write([]byte(strconv.Itoa(category) + ":" + strconv.Itoa(itemID)))
	return int(h.Sum32() % Specifics)
}

var beijing = time.FixedZone("CST", 8*3600)

// WeekStart is the start (Unix ms) of the expedition week containing now:
// the last resetWeekday resetHour:00 Beijing at or before now.
func (d *Data) WeekStart(now int64) int64 {
	t := time.UnixMilli(now).In(beijing)
	start := time.Date(t.Year(), t.Month(), t.Day(), d.Basic.ResetHour, 0, 0, 0, beijing)
	back := (int(t.Weekday()) - d.Basic.ResetWeekday + 7) % 7
	start = start.AddDate(0, 0, -back)
	if start.After(t) {
		start = start.AddDate(0, 0, -7)
	}
	return start.UnixMilli()
}

// DayStart is the start (Unix ms) of the friend day containing now (the
// friend list and its bonuses renew at friendResetHour Beijing).
func (d *Data) DayStart(now int64) int64 {
	t := time.UnixMilli(now).In(beijing)
	start := time.Date(t.Year(), t.Month(), t.Day(), d.Basic.FriendResetHour, 0, 0, 0, beijing)
	if start.After(t) {
		start = start.AddDate(0, 0, -1)
	}
	return start.UnixMilli()
}

// MissionIDs are the mission ids in table order.
func (d *Data) MissionIDs() []int {
	ids := make([]int, 0, len(d.Missions))
	for _, m := range d.Missions {
		ids = append(ids, m.ID)
	}
	sort.Ints(ids)
	return ids
}
