// Package career judges the My Room careers (成就, the original "Career"
// window dialog2_newCareer) and knows the emblems (徽章) they reward.
//
// careers.json is generated by rewrite/tools/export-career-data.mjs from the
// CN client's etc_/career/newCareer@cn.xml (judging and reward fields only),
// etc_/emblem/emblem@cn.xml and the time-attack track themes; it is embedded
// here and must never be edited by hand (the tests recompute its version).
//
// Every career of the table is shown. The data service can only measure
// some condition types (Tracked); the others never complete. A career is
// completed by the player (点击完成) once its value reaches clearValue; that
// stores it and grants its rewardPoint career points and its rewardEmblemId.
// The original item rewards (rewardStockId) are not granted.
package career

import (
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"
)

//go:embed careers.json
var embedded []byte

// Career is one careerItem of newCareer@cn.xml.
type Career struct {
	ID        int    `json:"id"`
	Main      int    `json:"main"`      // mainType: 1 普通, 2 多人游戏, 3 单人游戏, 4 车库
	Sub       int    `json:"sub"`       // subType, the window tab
	Type      int    `json:"type"`      // careerType (CareerData.h CareerType)
	Clear     int64  `json:"clear"`     // clearValue
	Point     int    `json:"point"`     // rewardPoint
	Emblem    int    `json:"emblem"`    // rewardEmblemId, 0 for none
	Theme     int    `json:"theme"`     // themeId, 0 for every theme
	GameType  int    `json:"gameType"`  // careerGameType, 0 for every game type
	Pre       int    `json:"pre"`       // preClearCareerId, 0 for none
	ItemCat   int    `json:"itemCat"`   // countItemCatId
	Items     []int  `json:"items"`     // countItemId
	Emblems   []int  `json:"emblems"`   // countEmblemId
	Multi     []int  `json:"multi"`     // multiId of a multi career
	Hidden    bool   `json:"hidden"`    // isHidden
	LucciZero bool   `json:"lucciZero"` // isLucciCheckZero
	Date      string `json:"date"`      // "MM-DD" of achievementDate
}

// Data is the embedded career table.
type Data struct {
	Version     string
	Careers     []Career
	byID        map[int]*Career
	emblems     map[int]bool
	EmblemIDs   []int
	trackThemes map[string]int
}

type document struct {
	Version     string         `json:"version"`
	Careers     []Career       `json:"careers"`
	Emblems     []int          `json:"emblems"`
	TrackThemes map[string]int `json:"trackThemes"`
}

// Parse reads a careers.json document.
func Parse(raw []byte) (*Data, error) {
	var doc document
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("careers.json: %w", err)
	}
	if doc.Version == "" || len(doc.Careers) == 0 || len(doc.Emblems) == 0 {
		return nil, errors.New("careers.json: missing version, careers or emblems")
	}
	data := &Data{Version: doc.Version, Careers: doc.Careers, byID: map[int]*Career{},
		emblems: map[int]bool{}, EmblemIDs: doc.Emblems, trackThemes: doc.TrackThemes}
	for _, id := range doc.Emblems {
		data.emblems[id] = true
	}
	for i := range data.Careers {
		c := &data.Careers[i]
		if c.ID <= 0 || data.byID[c.ID] != nil {
			return nil, fmt.Errorf("careers.json: bad or repeated career id %d", c.ID)
		}
		if c.Emblem != 0 && !data.emblems[c.Emblem] {
			return nil, fmt.Errorf("careers.json: career %d rewards unknown emblem %d", c.ID, c.Emblem)
		}
		data.byID[c.ID] = c
	}
	for _, c := range data.Careers {
		if c.Pre != 0 && data.byID[c.Pre] == nil {
			return nil, fmt.Errorf("careers.json: career %d needs unknown career %d", c.ID, c.Pre)
		}
		for _, id := range c.Multi {
			if data.byID[id] == nil {
				return nil, fmt.Errorf("careers.json: multi career %d names unknown career %d", c.ID, id)
			}
		}
	}
	return data, nil
}

var loadDefault = sync.OnceValues(func() (*Data, error) { return Parse(embedded) })

// Default returns the embedded table.
func Default() (*Data, error) { return loadDefault() }

// Career returns the career with id.
func (d *Data) Career(id int) (*Career, bool) {
	c, ok := d.byID[id]
	return c, ok
}

// Emblem reports whether id is an emblem of emblem@cn.xml.
func (d *Data) Emblem(id int) bool { return d.emblems[id] }

// themeNames are the track id prefixes of each career themeId, for tracks
// the time-attack catalog does not list (export-career-data THEME_IDS).
var themeNames = map[string]int{
	"forest": 1, "desert": 2, "village": 3, "ice": 4, "tomb": 5, "mine": 6, "northeu": 7, "factory": 8,
	"pirate": 9, "fairy": 10, "moonhill": 11, "gold": 12, "china": 13, "castle": 14, "nymph": 15,
	"mechanic": 16, "xyy": 17, "wkc": 18, "brodi": 19, "park": 20, "beach": 21, "steam": 22,
	"transformer": 23, "jurassic": 24, "world": 25, "nemo": 26, "sword": 27, "god": 28, "abyss": 29,
	"camelot": 30, "olympos": 31, "korea": 32, "mabi": 33, "maple": 34, "fengshen": 35,
}

// ThemeOf is the career themeId of a track: the catalog's theme, else the
// longest theme name the id starts with, else 0.
func (d *Data) ThemeOf(trackID string) int {
	if theme, ok := d.trackThemes[trackID]; ok {
		return theme
	}
	if theme, ok := d.trackThemes[strings.TrimSuffix(trackID, "_rvs")]; ok {
		return theme
	}
	lower, best, theme := strings.ToLower(trackID), 0, 0
	for name, id := range themeNames {
		if len(name) > best && strings.HasPrefix(lower, name) {
			best, theme = len(name), id
		}
	}
	return theme
}
