// Package economy holds the account-economy data exported from the original
// P3553 CN client (ECONOMY.md 1 and 3): the shop catalog (sellable items with
// their offers, tabs, the original mall layout and the new-rider starter
// whitelist), the level table with its level-up rewards, the time-attack
// track list and the shop's tcCash spend event.
//
// catalog.json, levels.json, tracks.json and events.json are generated by
// client/tools/export-economy-data.mjs and embedded here; never edit them by
// hand (economy tests recompute their content versions). The data service is
// the only consumer that may treat them as authoritative.
package economy

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

//go:embed catalog.json
var embeddedCatalog []byte

//go:embed levels.json
var embeddedLevels []byte

//go:embed tracks.json
var embeddedTracks []byte

//go:embed events.json
var embeddedEvents []byte

// Currency is one of the three wallet currencies (ECONOMY.md 0).
type Currency string

const (
	Coupon Currency = "coupon" // 点券, original priceType 0 (cash)
	Lucci  Currency = "lucci"  // 金币, original priceType 1
	Koin   Currency = "koin"   // K币 / 酷币, original priceType 3
)

// Currencies lists the wallet currencies in display order.
var Currencies = []Currency{Coupon, Lucci, Koin}

// Valid reports whether c is a wallet currency.
func (c Currency) Valid() bool { return slices.Contains(Currencies, c) }

// Offer sources.
const (
	SourceOriginal  = "original"  // a single-item stock of stock.kml
	SourceEstimated = "estimated" // priced by the exporter's category medians
)

// Item marks: the original card badges (stage_mqShop eventTag images) of
// the current shopCat.xml cards.
const (
	MarkNew      = "new"      // new@cn 新品 (shopMark new)
	MarkHot      = "hot"      // hot@cn 人气, the yellow star (shopMark hot)
	MarkDiscount = "discount" // discount<NN>@cn with the 折 label; some offer has OriginalPrice
	MarkLimited  = "limited"  // eventbuycount@cn 限购; some offer is Limited
)

// Kinds maps every sellable category to its itemTable kind: the categories
// the garage can equip (client garage-catalog.ts), plus the item changer
// vouchers (7 slotChanger, client/ITEM_MODE.md C.6), which no equipment
// slot holds.
var Kinds = map[int]string{
	1: "character", 2: "color", 3: "kart", 4: "plate", 7: "slotChanger", 8: "goggle", 9: "balloon",
	11: "headBand", 12: "headPhone", 16: "handGearL", 18: "uniform", 20: "decal",
	21: "pet", 26: "aura", 27: "skidMark", 31: "ridColor", 32: "rpLucciBonus",
	52: "flyingPet", 58: "goItemSkinCard", 61: "tachometer", 70: "dye", 71: "slotBg",
}

// Categories of the starter choices.
const (
	CategoryCharacter = 1
	CategoryPaint     = 2
	CategoryKart      = 3
	CategoryDye       = 70
)

// Offer is one purchasable option of an item. Price is what a purchase
// charges; the card fields after MinExp are display-only.
type Offer struct {
	OfferID  string   `json:"offerId"` // "s<stockId>" or "e<category>-<itemId>-<days>"
	Currency Currency `json:"currency"`
	Price    int64    `json:"price"`
	Days     int      `json:"days"`  // rental length; 0 = permanent
	Count    int      `json:"count"` // quantity granted (packs of count-based items)
	Source   string   `json:"source"`
	MinExp   int64    `json:"minExp,omitempty"` // buyer needs exp >= MinExp (original rpLimit)

	// OriginalPrice is the struck-through price of a discounted card
	// (shopCat.xml originalPrice); DiscountPercent is the NN of its
	// discount<NN> shopMark (percent off) and DiscountLabel the card's
	// "9折" / "5.6折" text. All three or none are set.
	OriginalPrice   int64  `json:"originalPrice,omitempty"`
	DiscountPercent int    `json:"discountPercent,omitempty"`
	DiscountLabel   string `json:"discountLabel,omitempty"`
	// Limited marks a 限购 card stock (stockCard eventBuyCount); BuyLimit is
	// that count when the card gives one. Not enforced by purchases.
	Limited  bool `json:"limited,omitempty"`
	BuyLimit int  `json:"buyLimit,omitempty"`
}

// Discounted reports whether the offer is shown with a struck-through price.
func (o Offer) Discounted() bool { return o.OriginalPrice > 0 }

// Permanent reports whether the offer never expires.
func (o Offer) Permanent() bool { return o.Days == 0 }

// Item is one sellable catalog item, keyed by (Category, ItemID).
type Item struct {
	Category   int    `json:"category"`
	ItemID     int    `json:"itemId"`
	Kind       string `json:"kind"`
	InternalID string `json:"internalId"`
	Name       string `json:"name"`
	Desc       string `json:"desc,omitempty"`
	// Tab and SubTab are the client's own layout (Catalog.Tabs).
	Tab    string `json:"tab"`
	SubTab string `json:"subTab"`
	// ShopCategory and ShopSubCategory place the item in the original mall
	// (Catalog.ShopTabs): kartBody/engineXun, equip/balloon, character (no
	// SubCat), useful/card, ... Couple equipment is listed under two SubCats:
	// ShopSubCategory is then "couple" and ShopSubCategories lists both, in
	// the ShopCat's SubCat order (absent = just ShopSubCategory).
	ShopCategory      string   `json:"shopCategory"`
	ShopSubCategory   string   `json:"shopSubCategory,omitempty"`
	ShopSubCategories []string `json:"shopSubCategories,omitempty"`
	EngineGrade       *int     `json:"engineGrade,omitempty"` // karts only
	KartType          int      `json:"kartType,omitempty"`    // karts only: 1 item kart, 2 speed kart
	IsAdditional      bool     `json:"isAdditional,omitempty"`
	Marks             []string `json:"marks,omitempty"` // badge kinds, MarkNew .. MarkLimited order
	// Recommend lists the 推荐 SubCats (new, hotItem, event) whose cards
	// list the item on the current recommand page.
	Recommend []string `json:"recommend,omitempty"`
	// DisplayOfferID is the offer the original card shows (its one price).
	DisplayOfferID string  `json:"displayOfferId"`
	Offers         []Offer `json:"offers"`
}

// InShopSubCategory reports whether the original lists the item under sub.
func (it *Item) InShopSubCategory(sub string) bool {
	if len(it.ShopSubCategories) > 0 {
		return slices.Contains(it.ShopSubCategories, sub)
	}
	return sub != "" && it.ShopSubCategory == sub
}

// DisplayOffer returns the offer the item's card shows.
func (it *Item) DisplayOffer() Offer {
	for _, offer := range it.Offers {
		if offer.OfferID == it.DisplayOfferID {
			return offer
		}
	}
	return it.Offers[0] // unreachable for validated catalogs
}

// Key returns the item's inventory key.
func (it *Item) Key() ItemKey { return ItemKey{Category: it.Category, ItemID: it.ItemID} }

// ItemKey identifies a catalog item (the inventory key without systemKey).
type ItemKey struct {
	Category int
	ItemID   int
}

// CurrencyInfo describes a wallet currency for display.
type CurrencyInfo struct {
	ID        Currency `json:"id"`
	Name      string   `json:"name"`
	PriceType int      `json:"priceType"`
}

// SubTab is a shop sub-tab.
type SubTab struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Tab is a top-level shop tab. "recommend" has no sub-tabs and lists items
// with Recommend set.
type Tab struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	SubTabs []SubTab `json:"subTabs"`
}

// RecommendTab is the tab that lists Item.Recommend items instead of owning items.
const RecommendTab = "recommend"

// ShopSubTab is a SubCat of an original mall tab.
type ShopSubTab struct {
	ID   string `json:"id"`   // shopCat.xml SubCat name
	Name string `json:"name"` // CN label (stage_mqShop / base string bag)
	// CardItems are the "category:itemId" keys the original cards list here,
	// in card order.
	CardItems []string `json:"cardItems"`
}

// ShopTab is a top-level tab of the original mall (shopCat.xml ShopCat):
// recommand (the current 推荐 page), kartBody, character, package, equip
// and useful.
type ShopTab struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// AllSubTab is the label of the leading 全部 sub-tab; empty when the
	// tab has none (推荐 and the tabs without SubCats).
	AllSubTab string `json:"allSubTab,omitempty"`
	// DefaultSubTab is the sub-tab selected on opening when there is no
	// 全部 (推荐: new).
	DefaultSubTab string       `json:"defaultSubTab,omitempty"`
	SubTabs       []ShopSubTab `json:"subTabs"`
	// CardItems are the card-listed items of a tab without SubCats.
	CardItems []string `json:"cardItems,omitempty"`
}

// ShopRecommendTab is the ShopTabs id of the 推荐 page; Item.Recommend
// lists its SubCats.
const ShopRecommendTab = "recommand"

// StarterKart is the free practice kart (a system kart: itemId 0 + systemKey).
type StarterKart struct {
	Category   int    `json:"category"`
	ItemID     int    `json:"itemId"`
	SystemKey  string `json:"systemKey"`
	InternalID string `json:"internalId"`
	Name       string `json:"name"`
}

// Starter is the new-rider gift whitelist (ECONOMY.md 4), from the original
// stage_/newRider/newRiderItem@cn.bml (characters, colors) and
// etc_/newRiderItem@cn.xml (the defaults: the dialog's initial picks). Paints
// and dyes share the original color list; every default is whitelisted.
type Starter struct {
	Kart             StarterKart `json:"kart"`
	Characters       []int       `json:"characters"`
	DefaultCharacter int         `json:"defaultCharacter"`
	Paints           []int       `json:"paints"`
	DefaultPaint     int         `json:"defaultPaint"`
	Dyes             []int       `json:"dyes"`
	DefaultDye       int         `json:"defaultDye"`
}

// AllowsCharacter reports whether a new rider may pick character itemID.
func (s *Starter) AllowsCharacter(itemID int) bool { return slices.Contains(s.Characters, itemID) }

// AllowsPaint reports whether a new rider may pick paint (category 2) itemID.
func (s *Starter) AllowsPaint(itemID int) bool { return slices.Contains(s.Paints, itemID) }

// AllowsDye reports whether a new rider may pick dye (category 70) itemID.
func (s *Starter) AllowsDye(itemID int) bool { return slices.Contains(s.Dyes, itemID) }

// Catalog is the shop catalog. All fields and returned values are shared
// read-only data.
type Catalog struct {
	Version       string         `json:"version"`
	GeneratedFrom string         `json:"generatedFrom"`
	Currencies    []CurrencyInfo `json:"currencies"`
	Tabs          []Tab          `json:"tabs"`
	ShopTabs      []ShopTab      `json:"shopTabs"`
	Starter       Starter        `json:"starter"`
	Items         []Item         `json:"items"`

	raw     []byte
	byKey   map[ItemKey]int
	byOffer map[string]offerRef
}

type offerRef struct{ item, offer int }

// ItemByKey returns the item with the given category and item id.
func (c *Catalog) ItemByKey(category, itemID int) (*Item, bool) {
	index, ok := c.byKey[ItemKey{Category: category, ItemID: itemID}]
	if !ok {
		return nil, false
	}
	return &c.Items[index], true
}

// OfferByID returns an offer and the item it sells.
func (c *Catalog) OfferByID(offerID string) (*Item, Offer, bool) {
	ref, ok := c.byOffer[offerID]
	if !ok {
		return nil, Offer{}, false
	}
	item := &c.Items[ref.item]
	return item, item.Offers[ref.offer], true
}

// OfferCount returns the number of offers across all items.
func (c *Catalog) OfferCount() int { return len(c.byOffer) }

// ShopTab returns the original mall tab with the given id.
func (c *Catalog) ShopTab(id string) (*ShopTab, bool) {
	for i := range c.ShopTabs {
		if c.ShopTabs[i].ID == id {
			return &c.ShopTabs[i], true
		}
	}
	return nil, false
}

// JSON returns the embedded catalog document exactly as generated, for
// serving GET /api/shop/catalog (ETag = Version). Do not modify it.
func (c *Catalog) JSON() []byte { return c.raw }

// Level is one row of the original level table. Level 0 is the pre-start
// row; displayed levels start at 1 (see Levels.LevelForExp).
type Level struct {
	Level     int    `json:"level"`
	NextExp   int64  `json:"nextExp,omitempty"` // cumulative exp that leaves this level; 0 on the last row
	Glove     string `json:"glove"`             // icon key: DataPack1 etc_/level/<glove>.png
	GloveName string `json:"gloveName"`
	TryLevel  int    `json:"tryLevel"` // highest driving-licence test the rider may try
}

// Levels is the CN level table (leveltable@cn.xml) plus level-up koin.
type Levels struct {
	Version       string        `json:"version"`
	GeneratedFrom string        `json:"generatedFrom"`
	RPLimit       int64         `json:"rpLimit"` // exp cap
	Levels        []Level       `json:"levels"`
	KoinRewards   map[int]int64 `json:"koinRewards"` // display level -> koin granted on reaching it

	raw []byte
}

// JSON returns the embedded levels document exactly as generated.
func (l *Levels) JSON() []byte { return l.raw }

// Data bundles the catalog, the level table, the time-attack tracks and
// the shop events.
type Data struct {
	Catalog *Catalog
	Levels  *Levels
	// Tracks is the time-attack track list; Load sets it, Parse leaves it
	// nil (callers then use DefaultTracks).
	Tracks *Tracks
	// Events are the shop's tcCash events; Load sets them, Parse leaves
	// them nil (callers then use DefaultEvents).
	Events *Events
}

// Load parses and validates the embedded catalog.json, levels.json,
// tracks.json and events.json.
func Load() (*Data, error) {
	data, err := Parse(embeddedCatalog, embeddedLevels)
	if err != nil {
		return nil, err
	}
	if data.Tracks, err = DefaultTracks(); err != nil {
		return nil, err
	}
	if data.Events, err = DefaultEvents(); err != nil {
		return nil, err
	}
	return data, nil
}

var loadDefault = sync.OnceValues(Load)

// Default returns the embedded data, parsed once per process.
func Default() (*Data, error) { return loadDefault() }

// Track is one time-attack track: an id the browser settles
// (POST /api/timeattack/settle trackId), "<id>_rvs" for a reverse track.
type Track struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	GameType string `json:"gameType"` // "item" or "speed"
	Reverse  bool   `json:"reverse,omitempty"`
}

// Tracks is the time-attack track list (tracks.json), exported from the
// the client's timeAttackTrackCatalog over the original track@zz.bml.
type Tracks struct {
	Version       string  `json:"version"`
	GeneratedFrom string  `json:"generatedFrom"`
	Tracks        []Track `json:"tracks"`

	ids map[string]bool
}

// Has reports whether id is a time-attack track (exact, case-sensitive).
func (t *Tracks) Has(id string) bool { return t.ids[id] }

// Len returns the number of tracks: the most distinct tracks an account
// can hold time-attack records on.
func (t *Tracks) Len() int { return len(t.Tracks) }

var trackIDPattern = regexp.MustCompile(`^[A-Za-z0-9_.-]{1,64}$`)

// ParseTracks decodes and validates a tracks.json document.
func ParseTracks(data []byte) (*Tracks, error) {
	tracks := &Tracks{}
	if err := decodeStrict(data, tracks); err != nil {
		return nil, fmt.Errorf("economy: tracks.json: %w", err)
	}
	if !versionPattern.MatchString(tracks.Version) {
		return nil, fmt.Errorf("economy: tracks.json: version %q is not a SHA-256 hex digest", tracks.Version)
	}
	if len(tracks.Tracks) == 0 {
		return nil, errors.New("economy: tracks.json: no tracks")
	}
	tracks.ids = make(map[string]bool, len(tracks.Tracks))
	for _, track := range tracks.Tracks {
		switch {
		case !trackIDPattern.MatchString(track.ID):
			return nil, fmt.Errorf("economy: tracks.json: invalid track id %q", track.ID)
		case tracks.ids[track.ID]:
			return nil, fmt.Errorf("economy: tracks.json: duplicate track %q", track.ID)
		case track.GameType != "item" && track.GameType != "speed":
			return nil, fmt.Errorf("economy: tracks.json: track %s has gameType %q", track.ID, track.GameType)
		case track.Title == "":
			return nil, fmt.Errorf("economy: tracks.json: track %s has no title", track.ID)
		}
		tracks.ids[track.ID] = true
	}
	return tracks, nil
}

var loadTracks = sync.OnceValues(func() (*Tracks, error) { return ParseTracks(embeddedTracks) })

// DefaultTracks returns the embedded track list, parsed once per process.
func DefaultTracks() (*Tracks, error) { return loadTracks() }

// SpendEventType is the tcCash event kind the shop runs: 累计消费, coupons
// (电池) spent in the shop.
const SpendEventType = "use"

// beijingOffset is the zone every event period is written in.
const beijingOffset = "+08:00"

// Period is a window of Beijing time from tcCashEvent.xml. Start and End are
// ISO 8601 with +08:00 and whole seconds; End is inclusive to the second
// ("...T05:59:59" lasts until 06:00:00), as the original writes it.
type Period struct {
	Start string `json:"start"`
	End   string `json:"end"`

	start, end time.Time
}

// Contains reports whether t falls in [Start, End + 1s).
func (p Period) Contains(t time.Time) bool {
	return !t.Before(p.start) && t.Before(p.end.Add(time.Second))
}

// Millis returns the period as [from, until) in Unix milliseconds.
func (p Period) Millis() (from, until int64) {
	return p.start.UnixMilli(), p.end.Add(time.Second).UnixMilli()
}

func (p *Period) parse() error {
	for _, field := range []struct {
		text   string
		target *time.Time
	}{{p.Start, &p.start}, {p.End, &p.end}} {
		at, err := time.Parse(time.RFC3339, field.text)
		if err != nil || !strings.HasSuffix(field.text, beijingOffset) || at.Nanosecond() != 0 {
			return fmt.Errorf("time %q is not ISO 8601 seconds with %s", field.text, beijingOffset)
		}
		*field.target = at
	}
	if !p.start.Before(p.end) {
		return fmt.Errorf("period %s ~ %s is empty", p.Start, p.End)
	}
	return nil
}

// EventReward is what a step grants in the original (display only here).
type EventReward struct {
	Name     string `json:"name"`
	Category int    `json:"category"`
	ItemID   int    `json:"itemId"`
	Count    int    `json:"count"`
	Days     int    `json:"days"` // 0 = permanent
	// IconHint is the shop catalog kind of a catalog item (e.g. "slotBg"),
	// otherwise "etc" (materials and boxes the shop does not sell).
	IconHint string `json:"iconHint"`
}

// EventStep is one reward threshold of a spend event.
type EventStep struct {
	Step    int         `json:"step"`
	Value   int64       `json:"value"`   // coupons spent in EventPeriod to reach the step
	StockID int         `json:"stockId"` // the original reward stock (stock.kml)
	Reward  EventReward `json:"reward"`
}

// SpendEvent is a tcCash 累计消费 event: coupons spent in the shop during
// EventPeriod count towards the steps; the original lets riders claim the
// rewards until RewardPeriod ends. Rewards are display-only here: the data
// service grants nothing.
type SpendEvent struct {
	EventType    string      `json:"eventType"`
	EventPeriod  Period      `json:"eventPeriod"`
	RewardPeriod Period      `json:"rewardPeriod"`
	Steps        []EventStep `json:"steps"`
}

// Active reports whether coupons spent at t count towards the event.
func (e *SpendEvent) Active(t time.Time) bool { return e.EventPeriod.Contains(t) }

// Shown reports whether the event is shown at t: from the start of the
// event period to the end of the reward period.
func (e *SpendEvent) Shown(t time.Time) bool {
	return !t.Before(e.EventPeriod.start) && t.Before(e.RewardPeriod.end.Add(time.Second))
}

// Events is events.json: the shop's tcCash events, exported from
// zeta_/cn/content/tcCashEvent.xml.
type Events struct {
	Version       string       `json:"version"`
	GeneratedFrom string       `json:"generatedFrom"`
	TCCashEvents  []SpendEvent `json:"tcCashEvents"`
}

// SpendEventAt returns the spend event shown at t (SpendEvent.Shown), the
// latest-starting one when several are.
func (e *Events) SpendEventAt(t time.Time) (*SpendEvent, bool) {
	var found *SpendEvent
	for i := range e.TCCashEvents {
		event := &e.TCCashEvents[i]
		if event.EventType == SpendEventType && event.Shown(t) &&
			(found == nil || event.EventPeriod.start.After(found.EventPeriod.start)) {
			found = event
		}
	}
	return found, found != nil
}

// ParseEvents decodes and validates an events.json document.
func ParseEvents(data []byte) (*Events, error) {
	events := &Events{}
	if err := decodeStrict(data, events); err != nil {
		return nil, fmt.Errorf("economy: events.json: %w", err)
	}
	if !versionPattern.MatchString(events.Version) {
		return nil, fmt.Errorf("economy: events.json: version %q is not a SHA-256 hex digest", events.Version)
	}
	for i := range events.TCCashEvents {
		if err := events.TCCashEvents[i].validate(); err != nil {
			return nil, fmt.Errorf("economy: events.json: event %d: %w", i, err)
		}
	}
	return events, nil
}

func (e *SpendEvent) validate() error {
	if e.EventType != SpendEventType {
		return fmt.Errorf("eventType %q, only %q is supported", e.EventType, SpendEventType)
	}
	if err := e.EventPeriod.parse(); err != nil {
		return fmt.Errorf("eventPeriod: %w", err)
	}
	if err := e.RewardPeriod.parse(); err != nil {
		return fmt.Errorf("rewardPeriod: %w", err)
	}
	if e.RewardPeriod.start.After(e.EventPeriod.start) || e.RewardPeriod.end.Before(e.EventPeriod.end) {
		return errors.New("rewardPeriod does not cover eventPeriod")
	}
	if len(e.Steps) == 0 {
		return errors.New("no steps")
	}
	for i, step := range e.Steps {
		reward := step.Reward
		switch {
		case step.Step != i+1:
			return fmt.Errorf("step %d at position %d", step.Step, i+1)
		case step.Value <= 0 || (i > 0 && step.Value <= e.Steps[i-1].Value):
			return fmt.Errorf("step %d: value %d must be positive and increasing", step.Step, step.Value)
		case step.StockID <= 0:
			return fmt.Errorf("step %d: stockId %d", step.Step, step.StockID)
		case reward.Name == "" || reward.IconHint == "" || reward.Category < 0 || reward.ItemID < 0 ||
			reward.Count < 1 || reward.Days < 0:
			return fmt.Errorf("step %d: invalid reward %+v", step.Step, reward)
		}
	}
	return nil
}

var loadEvents = sync.OnceValues(func() (*Events, error) { return ParseEvents(embeddedEvents) })

// DefaultEvents returns the embedded events, parsed once per process.
func DefaultEvents() (*Events, error) { return loadEvents() }

// Parse decodes and validates a catalog and a level document. Unknown JSON
// fields are rejected so exporter and server schema changes stay in step.
func Parse(catalogJSON, levelsJSON []byte) (*Data, error) {
	catalog := &Catalog{}
	if err := decodeStrict(catalogJSON, catalog); err != nil {
		return nil, fmt.Errorf("economy: catalog.json: %w", err)
	}
	catalog.raw = catalogJSON
	if err := catalog.index(); err != nil {
		return nil, fmt.Errorf("economy: catalog.json: %w", err)
	}
	levels := &Levels{}
	if err := decodeStrict(levelsJSON, levels); err != nil {
		return nil, fmt.Errorf("economy: levels.json: %w", err)
	}
	levels.raw = levelsJSON
	if err := levels.validate(); err != nil {
		return nil, fmt.Errorf("economy: levels.json: %w", err)
	}
	return &Data{Catalog: catalog, Levels: levels}, nil
}

func decodeStrict(data []byte, target any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return err
	}
	if _, err := decoder.Token(); !errors.Is(err, io.EOF) {
		return errors.New("trailing data after the JSON document")
	}
	return nil
}

var (
	versionPattern   = regexp.MustCompile(`^[0-9a-f]{64}$`)
	originalOfferID  = regexp.MustCompile(`^s[1-9][0-9]*$`)
	estimatedOfferID = regexp.MustCompile(`^e([0-9]+)-([0-9]+)-([0-9]+)$`)
	knownMarks       = []string{MarkNew, MarkHot, MarkDiscount, MarkLimited}
	itemKeyPattern   = regexp.MustCompile(`^([1-9][0-9]*):([1-9][0-9]*)$`)
)

func (c *Catalog) index() error {
	if !versionPattern.MatchString(c.Version) {
		return fmt.Errorf("version %q is not a SHA-256 hex digest", c.Version)
	}
	if err := c.validateCurrencies(); err != nil {
		return err
	}
	subTabs, err := c.validateTabs()
	if err != nil {
		return err
	}
	shop, err := c.validateShopTabs()
	if err != nil {
		return err
	}
	if len(c.Items) == 0 {
		return errors.New("no items")
	}
	c.byKey = make(map[ItemKey]int, len(c.Items))
	c.byOffer = make(map[string]offerRef, 2*len(c.Items))
	for index := range c.Items {
		item := &c.Items[index]
		if err := validateItem(item, subTabs); err != nil {
			return fmt.Errorf("item %d:%d: %w", item.Category, item.ItemID, err)
		}
		if err := shop.validateItem(item); err != nil {
			return fmt.Errorf("item %d:%d: %w", item.Category, item.ItemID, err)
		}
		if _, dup := c.byKey[item.Key()]; dup {
			return fmt.Errorf("duplicate item %d:%d", item.Category, item.ItemID)
		}
		c.byKey[item.Key()] = index
		for offerIndex, offer := range item.Offers {
			if _, dup := c.byOffer[offer.OfferID]; dup {
				return fmt.Errorf("duplicate offerId %s", offer.OfferID)
			}
			c.byOffer[offer.OfferID] = offerRef{item: index, offer: offerIndex}
		}
	}
	if err := c.validateCardItems(); err != nil {
		return err
	}
	return c.validateStarter()
}

// shopLayout is the validated ShopTabs: tab id -> SubCat ids in order.
type shopLayout map[string][]string

// validateShopTabs checks the original mall tabs: unique ids, labels, the
// recommand tab with its SubCats and default, 全部 only on SubCat tabs.
func (c *Catalog) validateShopTabs() (shopLayout, error) {
	layout := shopLayout{}
	for _, tab := range c.ShopTabs {
		if tab.ID == "" || tab.Name == "" {
			return nil, fmt.Errorf("shop tab %q has no id or name", tab.ID)
		}
		if _, dup := layout[tab.ID]; dup {
			return nil, fmt.Errorf("duplicate shop tab %q", tab.ID)
		}
		subs := make([]string, 0, len(tab.SubTabs))
		for _, sub := range tab.SubTabs {
			if sub.ID == "" || sub.Name == "" || slices.Contains(subs, sub.ID) {
				return nil, fmt.Errorf("shop tab %s: invalid or duplicate sub-tab %q", tab.ID, sub.ID)
			}
			subs = append(subs, sub.ID)
		}
		switch {
		case len(subs) == 0 && (tab.AllSubTab != "" || tab.DefaultSubTab != ""):
			return nil, fmt.Errorf("shop tab %s has no sub-tabs but a 全部 or default sub-tab", tab.ID)
		case len(subs) > 0 && len(tab.CardItems) > 0:
			return nil, fmt.Errorf("shop tab %s lists card items outside its sub-tabs", tab.ID)
		case len(subs) > 0 && tab.AllSubTab == "" && tab.DefaultSubTab == "":
			return nil, fmt.Errorf("shop tab %s needs a 全部 or a default sub-tab", tab.ID)
		case tab.DefaultSubTab != "" && !slices.Contains(subs, tab.DefaultSubTab):
			return nil, fmt.Errorf("shop tab %s: default sub-tab %q is not one of its sub-tabs", tab.ID, tab.DefaultSubTab)
		}
		layout[tab.ID] = subs
	}
	if len(layout[ShopRecommendTab]) == 0 {
		return nil, fmt.Errorf("missing shop tab %q with sub-tabs", ShopRecommendTab)
	}
	if recommend, _ := c.ShopTab(ShopRecommendTab); recommend.AllSubTab != "" {
		return nil, fmt.Errorf("shop tab %s has no 全部 in the original", ShopRecommendTab)
	}
	return layout, nil
}

// validateItem checks an item's place in the original mall, its 推荐
// SubCats, badges and card offer.
func (layout shopLayout) validateItem(item *Item) error {
	subs, known := layout[item.ShopCategory]
	switch {
	case !known || item.ShopCategory == ShopRecommendTab:
		return fmt.Errorf("unknown shopCategory %q", item.ShopCategory)
	case len(subs) == 0 && (item.ShopSubCategory != "" || len(item.ShopSubCategories) > 0):
		return fmt.Errorf("shopCategory %s has no sub-categories", item.ShopCategory)
	case len(subs) > 0 && !slices.Contains(subs, item.ShopSubCategory):
		return fmt.Errorf("unknown shopSubCategory %s/%s", item.ShopCategory, item.ShopSubCategory)
	}
	if len(item.ShopSubCategories) > 0 {
		if len(item.ShopSubCategories) < 2 || !slices.Contains(item.ShopSubCategories, item.ShopSubCategory) {
			return errors.New("shopSubCategories must list shopSubCategory and another sub-category")
		}
		if err := inOrder(item.ShopSubCategories, subs); err != nil {
			return fmt.Errorf("shopSubCategories: %w", err)
		}
	}
	if err := inOrder(item.Recommend, layout[ShopRecommendTab]); err != nil {
		return fmt.Errorf("recommend: %w", err)
	}
	marks := map[string]bool{}
	for _, mark := range item.Marks {
		if !slices.Contains(knownMarks, mark) || marks[mark] {
			return fmt.Errorf("unknown or repeated mark %q", mark)
		}
		marks[mark] = true
	}
	discounted := slices.ContainsFunc(item.Offers, Offer.Discounted)
	limited := slices.ContainsFunc(item.Offers, func(offer Offer) bool { return offer.Limited })
	switch {
	case marks[MarkDiscount] != discounted:
		return fmt.Errorf("mark %q without a discounted offer, or the reverse", MarkDiscount)
	case marks[MarkLimited] != limited:
		return fmt.Errorf("mark %q without a limited offer, or the reverse", MarkLimited)
	case !slices.ContainsFunc(item.Offers, func(offer Offer) bool { return offer.OfferID == item.DisplayOfferID }):
		return fmt.Errorf("displayOfferId %q is not one of its offers", item.DisplayOfferID)
	}
	return nil
}

// inOrder checks that values are distinct members of order, in its order.
func inOrder(values, order []string) error {
	last := -1
	for _, value := range values {
		at := slices.Index(order, value)
		if at < 0 {
			return fmt.Errorf("unknown %q", value)
		}
		if at <= last {
			return fmt.Errorf("%q repeated or out of order", value)
		}
		last = at
	}
	return nil
}

// validateCardItems checks that every card-listed item exists and belongs
// where it is listed, and that 推荐 lists exactly the items naming it.
func (c *Catalog) validateCardItems() error {
	for _, tab := range c.ShopTabs {
		lists := []struct {
			sub   string
			items []string
		}{{"", tab.CardItems}}
		for _, sub := range tab.SubTabs {
			lists = append(lists, struct {
				sub   string
				items []string
			}{sub.ID, sub.CardItems})
		}
		for _, list := range lists {
			seen := map[string]bool{}
			for _, key := range list.items {
				item, err := c.itemByText(key)
				if err != nil || seen[key] {
					return fmt.Errorf("shop tab %s/%s: card item %q unknown or repeated", tab.ID, list.sub, key)
				}
				seen[key] = true
				var member bool
				if tab.ID == ShopRecommendTab {
					member = slices.Contains(item.Recommend, list.sub)
				} else {
					member = item.ShopCategory == tab.ID && (list.sub == "" || item.InShopSubCategory(list.sub))
				}
				if !member {
					return fmt.Errorf("shop tab %s/%s lists %s, which is not placed there", tab.ID, list.sub, key)
				}
			}
			if tab.ID != ShopRecommendTab || list.sub == "" {
				continue
			}
			for i := range c.Items {
				item := &c.Items[i]
				if slices.Contains(item.Recommend, list.sub) && !seen[fmt.Sprintf("%d:%d", item.Category, item.ItemID)] {
					return fmt.Errorf("item %d:%d names 推荐 %s, which does not list it", item.Category, item.ItemID, list.sub)
				}
			}
		}
	}
	return nil
}

// itemByText resolves a "category:itemId" card item key.
func (c *Catalog) itemByText(key string) (*Item, error) {
	match := itemKeyPattern.FindStringSubmatch(key)
	if match == nil {
		return nil, fmt.Errorf("invalid item key %q", key)
	}
	category, err1 := strconv.Atoi(match[1])
	itemID, err2 := strconv.Atoi(match[2])
	if err1 != nil || err2 != nil {
		return nil, fmt.Errorf("invalid item key %q", key)
	}
	item, ok := c.ItemByKey(category, itemID)
	if !ok {
		return nil, fmt.Errorf("unknown item %q", key)
	}
	return item, nil
}

func (c *Catalog) validateCurrencies() error {
	seen := map[Currency]bool{}
	for _, info := range c.Currencies {
		if !info.ID.Valid() || info.Name == "" || seen[info.ID] {
			return fmt.Errorf("invalid or duplicate currency %q", info.ID)
		}
		seen[info.ID] = true
	}
	if len(seen) != len(Currencies) {
		return fmt.Errorf("currencies lists %d of %d wallet currencies", len(seen), len(Currencies))
	}
	return nil
}

// validateTabs returns the valid "tab/subTab" pairs.
func (c *Catalog) validateTabs() (map[string]bool, error) {
	pairs := map[string]bool{}
	tabs := map[string]bool{}
	for _, tab := range c.Tabs {
		if tab.ID == "" || tab.Name == "" || tabs[tab.ID] {
			return nil, fmt.Errorf("invalid or duplicate tab %q", tab.ID)
		}
		tabs[tab.ID] = true
		for _, sub := range tab.SubTabs {
			key := tab.ID + "/" + sub.ID
			if sub.ID == "" || sub.Name == "" || pairs[key] {
				return nil, fmt.Errorf("invalid or duplicate sub-tab %q", key)
			}
			pairs[key] = true
		}
	}
	if !tabs[RecommendTab] {
		return nil, fmt.Errorf("missing %q tab", RecommendTab)
	}
	return pairs, nil
}

func validateItem(item *Item, subTabs map[string]bool) error {
	kind, known := Kinds[item.Category]
	switch {
	case !known:
		return errors.New("category is not sellable")
	case item.Kind != kind:
		return fmt.Errorf("kind %q, category %d is %q", item.Kind, item.Category, kind)
	case item.ItemID <= 0:
		return errors.New("itemId must be positive (system karts are not sold)")
	case item.Name == "" || item.InternalID == "":
		return errors.New("empty name or internalId")
	case !subTabs[item.Tab+"/"+item.SubTab]:
		return fmt.Errorf("unknown tab %s/%s", item.Tab, item.SubTab)
	}
	if item.Category == CategoryKart {
		if item.EngineGrade == nil || *item.EngineGrade < 0 || (item.KartType != 1 && item.KartType != 2) {
			return errors.New("kart needs engineGrade >= 0 and kartType 1 or 2")
		}
	} else if item.EngineGrade != nil || item.KartType != 0 {
		return errors.New("engineGrade/kartType on a non-kart")
	}
	for _, mark := range item.Marks {
		if !slices.Contains(knownMarks, mark) {
			return fmt.Errorf("unknown mark %q", mark)
		}
	}
	if len(item.Offers) == 0 {
		return errors.New("no offers")
	}
	groups := map[string]bool{}
	for _, offer := range item.Offers {
		if err := validateOffer(item, offer); err != nil {
			return fmt.Errorf("offer %s: %w", offer.OfferID, err)
		}
		group := fmt.Sprintf("%s/%d/%d", offer.Currency, offer.Days, offer.Count)
		if groups[group] {
			return fmt.Errorf("two offers for %s", group)
		}
		groups[group] = true
	}
	return nil
}

func validateOffer(item *Item, offer Offer) error {
	switch {
	case !offer.Currency.Valid():
		return fmt.Errorf("unknown currency %q", offer.Currency)
	case offer.Price < 1:
		return fmt.Errorf("price %d", offer.Price)
	case offer.Days < 0:
		return fmt.Errorf("days %d", offer.Days)
	case offer.Count < 1:
		return fmt.Errorf("count %d", offer.Count)
	case offer.MinExp < 0:
		return fmt.Errorf("minExp %d", offer.MinExp)
	case offer.OriginalPrice < 0 || offer.BuyLimit < 0:
		return errors.New("negative originalPrice or buyLimit")
	case offer.Discounted() && (offer.OriginalPrice <= offer.Price || offer.DiscountPercent < 1 ||
		offer.DiscountPercent > 99 || offer.DiscountLabel == ""):
		return fmt.Errorf("discount %d -> %d (%d%%, %q)", offer.OriginalPrice, offer.Price, offer.DiscountPercent,
			offer.DiscountLabel)
	case !offer.Discounted() && (offer.DiscountPercent != 0 || offer.DiscountLabel != ""):
		return errors.New("discountPercent or discountLabel without originalPrice")
	case offer.BuyLimit > 0 && !offer.Limited:
		return errors.New("buyLimit on an offer that is not limited")
	}
	switch offer.Source {
	case SourceOriginal:
		if !originalOfferID.MatchString(offer.OfferID) {
			return errors.New("original offers are named s<stockId>")
		}
	case SourceEstimated:
		match := estimatedOfferID.FindStringSubmatch(offer.OfferID)
		if match == nil || match[1] != strconv.Itoa(item.Category) ||
			match[2] != strconv.Itoa(item.ItemID) || match[3] != strconv.Itoa(offer.Days) {
			return errors.New("estimated offers are named e<category>-<itemId>-<days>")
		}
	default:
		return fmt.Errorf("unknown source %q", offer.Source)
	}
	return nil
}

func (c *Catalog) validateStarter() error {
	s := &c.Starter
	if s.Kart.Category != CategoryKart || s.Kart.ItemID != 0 || s.Kart.SystemKey == "" ||
		s.Kart.InternalID == "" || s.Kart.Name == "" {
		return errors.New("starter kart must be a category-3 system kart (itemId 0 + systemKey)")
	}
	for _, list := range []struct {
		name     string
		ids      []int
		category int
		def      int
	}{{"characters", s.Characters, CategoryCharacter, s.DefaultCharacter},
		{"paints", s.Paints, CategoryPaint, s.DefaultPaint}, {"dyes", s.Dyes, CategoryDye, s.DefaultDye}} {
		if len(list.ids) == 0 {
			return fmt.Errorf("starter %s is empty", list.name)
		}
		seen := map[int]bool{}
		for _, id := range list.ids {
			if seen[id] {
				return fmt.Errorf("starter %s lists %d twice", list.name, id)
			}
			seen[id] = true
			if _, ok := c.ItemByKey(list.category, id); !ok {
				return fmt.Errorf("starter %s item %d:%d is not in the catalog", list.name, list.category, id)
			}
		}
		if !seen[list.def] {
			return fmt.Errorf("starter default %d is not one of the %s", list.def, list.name)
		}
	}
	return nil
}

func (l *Levels) validate() error {
	if !versionPattern.MatchString(l.Version) {
		return fmt.Errorf("version %q is not a SHA-256 hex digest", l.Version)
	}
	if len(l.Levels) < 2 {
		return errors.New("need at least two levels")
	}
	last := len(l.Levels) - 1
	for index, level := range l.Levels {
		switch {
		case level.Level != index:
			return fmt.Errorf("row %d has level %d", index, level.Level)
		case level.Glove == "" || level.GloveName == "":
			return fmt.Errorf("level %d: empty glove", index)
		case index == last && level.NextExp != 0:
			return fmt.Errorf("max level %d must not have nextExp", index)
		case index < last && level.NextExp <= 0:
			return fmt.Errorf("level %d: nextExp %d", index, level.NextExp)
		case index > 0 && index < last && level.NextExp <= l.Levels[index-1].NextExp:
			return fmt.Errorf("level %d: nextExp %d not increasing", index, level.NextExp)
		}
	}
	if l.RPLimit <= l.Levels[last-1].NextExp {
		return fmt.Errorf("rpLimit %d does not exceed the last threshold", l.RPLimit)
	}
	for level, koin := range l.KoinRewards {
		if level < 1 || level > last || koin <= 0 {
			return fmt.Errorf("koin reward %d at level %d", koin, level)
		}
	}
	return nil
}

// MaxLevel returns the highest level.
func (l *Levels) MaxLevel() int { return len(l.Levels) - 1 }

// Progress is a rider's level state (the /api/account "progress" object).
type Progress struct {
	Level         int    `json:"level"`        // displayed level, >= 1
	Exp           int64  `json:"exp"`          // exp clamped to [0, RPLimit]
	LevelStartExp int64  `json:"levelExp"`     // exp at which Level starts
	NextLevelExp  int64  `json:"nextLevelExp"` // exp that reaches Level+1; RPLimit at the max level
	Glove         string `json:"glove"`
	GloveName     string `json:"gloveName"`
	MaxLevel      int    `json:"maxLevel"`
}

// LevelForExp maps cumulative exp to a level (ECONOMY.md 1): the table level
// L is the largest with exp >= nextExp[L-1] (nextExp[-1] = 0), displayed as
// max(1, L). Level 0 (exp 0) is folded into level 1, so level 1 spans
// [0, nextExp[1]). Exp is clamped to [0, RPLimit]; at the max level the
// progress bar runs from its threshold to RPLimit.
func (l *Levels) LevelForExp(exp int64) Progress {
	exp = min(max(exp, 0), l.RPLimit)
	last := l.MaxLevel()
	table := sort.Search(last, func(i int) bool { return l.Levels[i].NextExp > exp })
	level := max(1, table)
	progress := Progress{Level: level, Exp: exp, Glove: l.Levels[level].Glove,
		GloveName: l.Levels[level].GloveName, MaxLevel: last}
	if level > 1 {
		progress.LevelStartExp = l.Levels[level-1].NextExp
	}
	progress.NextLevelExp = l.RPLimit
	if level < last {
		progress.NextLevelExp = l.Levels[level].NextExp
	}
	return progress
}

// Level-up reward rules (ECONOMY.md 1).
const (
	LucciPerLevel       = 100 // lucci = 100 x the level reached
	CouponLevelInterval = 10  // every 10th level ...
	CouponPerInterval   = 50  // ... grants 50 coupons
)

// LevelReward is what reaching one level grants.
type LevelReward struct {
	Level  int   `json:"level"`
	Lucci  int64 `json:"lucci"`
	Koin   int64 `json:"koin"`
	Coupon int64 `json:"coupon"`
}

// LevelUpRewards lists the rewards for each displayed level reached when a
// rider goes from fromLevel to toLevel, one entry per level in
// (fromLevel, toLevel], so each can be written to the ledger. Levels are
// clamped to [1, MaxLevel]; no level-up yields nil.
func (l *Levels) LevelUpRewards(fromLevel, toLevel int) []LevelReward {
	fromLevel = max(fromLevel, 1)
	toLevel = min(toLevel, l.MaxLevel())
	if toLevel <= fromLevel {
		return nil
	}
	rewards := make([]LevelReward, 0, toLevel-fromLevel)
	for level := fromLevel + 1; level <= toLevel; level++ {
		reward := LevelReward{Level: level, Lucci: LucciPerLevel * int64(level), Koin: l.KoinRewards[level]}
		if level%CouponLevelInterval == 0 {
			reward.Coupon = CouponPerInterval
		}
		rewards = append(rewards, reward)
	}
	return rewards
}

// LevelUpsForExp returns LevelUpRewards between the levels of two exp totals.
func (l *Levels) LevelUpsForExp(oldExp, newExp int64) []LevelReward {
	return l.LevelUpRewards(l.LevelForExp(oldExp).Level, l.LevelForExp(newExp).Level)
}

// TotalReward sums level rewards; the Level field is the last level reached.
func TotalReward(rewards []LevelReward) LevelReward {
	var total LevelReward
	for _, reward := range rewards {
		total.Level = reward.Level
		total.Lucci += reward.Lucci
		total.Koin += reward.Koin
		total.Coupon += reward.Coupon
	}
	return total
}
