// Package lottery knows the original boxes (category-24 items, 开箱): which
// reward sets a box draws from at a given time and the stocks they give.
//
// lottery.json is generated by rewrite/tools/export-lottery-data.mjs from the
// CN client's zeta_/cn/lottery/lottery.xml, stock.kml and item.kml; it is
// embedded here and must never be edited by hand (the tests recompute its
// version).
package lottery

import (
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"sync"
)

//go:embed lottery.json
var embedded []byte

// Category is the item category of boxes.
const Category = 24

// Item is one item of a reward stock.
type Item struct {
	Category int `json:"category"`
	ItemID   int `json:"itemId"`
	Count    int `json:"count"`
	Days     int `json:"days"` // 0: permanent
}

// Reward is one weighted entry of a reward set.
type Reward struct {
	StockID int `json:"stockId"`
	Weight  int `json:"weight"`
	Summary int `json:"summary,omitempty"` // the order of the highlighted prizes
}

// List is a dated rewardList row: the sets a box draws from in [From, To)
// (Unix ms; 0 is open).
type List struct {
	From int64 `json:"from"`
	To   int64 `json:"to"`
	Sets []int `json:"sets"`
}

// Lottery is one box.
type Lottery struct {
	ID        int    `json:"id"`
	Caption   string `json:"caption,omitempty"`
	Desc      string `json:"desc,omitempty"`
	NeedOther int    `json:"needOther,omitempty"` // a key box (category 24) opening it takes
	Retry     int    `json:"retry,omitempty"`     // redraws of a prize already owned permanently
	RpLimit   int    `json:"rpLimit,omitempty"`   // the exp an account needs
	Lists     []List `json:"lists"`
}

// Data is the embedded table.
type Data struct {
	Version   string
	lotteries map[int]*Lottery
	sets      map[int][]Reward
	stocks    map[int][]Item
	names     map[string]string
}

// Parse reads a lottery.json document.
func Parse(raw []byte) (*Data, error) {
	var doc struct {
		Version   string              `json:"version"`
		Lotteries []Lottery           `json:"lotteries"`
		Sets      map[string][]Reward `json:"sets"`
		Stocks    map[string][]Item   `json:"stocks"`
		Names     map[string]string   `json:"names"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("lottery.json: %w", err)
	}
	if doc.Version == "" || len(doc.Lotteries) == 0 {
		return nil, errors.New("lottery.json: missing version or lotteries")
	}
	d := &Data{Version: doc.Version, lotteries: map[int]*Lottery{}, sets: map[int][]Reward{},
		stocks: map[int][]Item{}, names: doc.Names}
	for key, items := range doc.Stocks {
		id, err := strconv.Atoi(key)
		if err != nil || len(items) == 0 {
			return nil, fmt.Errorf("lottery.json: stock %q", key)
		}
		d.stocks[id] = items
	}
	for key, rewards := range doc.Sets {
		id, err := strconv.Atoi(key)
		if err != nil {
			return nil, fmt.Errorf("lottery.json: set %q", key)
		}
		for _, reward := range rewards {
			if reward.Weight < 0 || d.stocks[reward.StockID] == nil {
				return nil, fmt.Errorf("lottery.json: set %d reward %+v", id, reward)
			}
		}
		d.sets[id] = rewards
	}
	for i := range doc.Lotteries {
		l := &doc.Lotteries[i]
		if d.lotteries[l.ID] != nil {
			return nil, fmt.Errorf("lottery.json: lottery %d repeated", l.ID)
		}
		for _, list := range l.Lists {
			for _, set := range list.Sets {
				if _, ok := d.sets[set]; !ok {
					return nil, fmt.Errorf("lottery.json: lottery %d names unknown set %d", l.ID, set)
				}
			}
		}
		d.lotteries[l.ID] = l
	}
	return d, nil
}

var loadDefault = sync.OnceValues(func() (*Data, error) { return Parse(embedded) })

// Default returns the embedded table.
func Default() (*Data, error) { return loadDefault() }

// Lottery returns the box with item id.
func (d *Data) Lottery(id int) (*Lottery, bool) {
	l, ok := d.lotteries[id]
	return l, ok
}

// Name is an item's CN name ("" when item.kml has none).
func (d *Data) Name(category, itemID int) string {
	return d.names[strconv.Itoa(category)+":"+strconv.Itoa(itemID)]
}

// Stock returns a reward stock's items.
func (d *Data) Stock(id int) []Item { return d.stocks[id] }

// Rewards are the weighted rewards a box draws from at now (Unix ms): the
// sets of its first rewardList row in effect; nil when none is.
func (d *Data) Rewards(l *Lottery, now int64) []Reward {
	for _, list := range l.Lists {
		if (list.From != 0 && now < list.From) || (list.To != 0 && now >= list.To) {
			continue
		}
		var rewards []Reward
		for _, set := range list.Sets {
			rewards = append(rewards, d.sets[set]...)
		}
		return rewards
	}
	return nil
}

// Draw picks a reward by weight; roll returns a uniform integer in [0, n).
// It returns false when the rewards weigh nothing.
func Draw(rewards []Reward, roll func(n int) int) (Reward, bool) {
	total := 0
	for _, reward := range rewards {
		total += reward.Weight
	}
	if total <= 0 {
		return Reward{}, false
	}
	pick := roll(total)
	for _, reward := range rewards {
		if pick < reward.Weight {
			return reward, true
		}
		pick -= reward.Weight
	}
	return rewards[len(rewards)-1], true
}
