// Package lottery holds the original CN lottery tables (LOTTERY.md): the
// 扭蛋 / 开箱 lotteries keyed by their category-24 item, the 寻宝 (treasure
// hunt) reward table, lottery mileage (保底) prizes and the original packs
// that sell the materials, plus the pure draw rules. The data service's
// store applies the results to inventories.
//
// lottery.json is generated by rewrite/tools/export-lottery-data.mjs and
// embedded here; never edit it by hand (version_test.go recomputes its
// content version).
package lottery

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"regexp"
	"slices"
	"sort"
	"strings"
	"sync"
	"time"

	"kartsim/internal/data/economy"
)

//go:embed lottery.json
var embedded []byte

// Category is the item category of the lottery items themselves.
const Category = 24

// MaterialCategory is the category of the treasure-hunt materials
// (寻宝放大镜, 幸运藏宝图).
const MaterialCategory = 34

// Currency items a reward may grant: they credit the wallet instead of the
// inventory (item.kml 56:1 酷币 is the koin, 62:1 电池 the coupon).
var currencyItems = map[ItemKey]economy.Currency{
	{Category: 56, ItemID: 1}: economy.Koin,
	{Category: 62, ItemID: 1}: economy.Coupon,
}

// ItemKey identifies an item.
type ItemKey struct {
	Category int `json:"category"`
	ItemID   int `json:"itemId"`
}

func (k ItemKey) String() string { return fmt.Sprintf("%d:%d", k.Category, k.ItemID) }

// CurrencyOf reports the wallet currency an item stands for.
func CurrencyOf(key ItemKey) (economy.Currency, bool) {
	currency, ok := currencyItems[key]
	return currency, ok
}

// Lottery is one lottery item (lottery.xml <lottery>): using it draws one
// reward from each of Sets. Key, when set, is a second category-24 item
// consumed with every use (变形齿轮, 幸运车胎).
type Lottery struct {
	ItemID  int    `json:"itemId"`
	Name    string `json:"name"`
	Caption string `json:"caption,omitempty"` // dialogCaption when it differs from Name
	Desc    string `json:"desc,omitempty"`    // dialogDesc ("|" breaks lines)
	Effect  string `json:"effect,omitempty"`  // item.kml itemEffect
	Dialog  string `json:"dialog,omitempty"`  // openDialog: new_gacha (精品道具场), levelupBox
	Start   string `json:"start,omitempty"`   // the original reward-list period (informational)
	End     string `json:"end,omitempty"`
	Key     int    `json:"key,omitempty"`
	Sets    []int  `json:"sets"`
	// Retry (retryCount) and RpLimit are rules of the 我的物品 box opening
	// (Rewards / Draw, store OpenBox): redraws of a prize owned permanently
	// and the exp an account needs.
	Retry   int `json:"retry,omitempty"`
	RpLimit int `json:"rpLimit,omitempty"`

	from, until int64 // the original period in Unix ms; 0 is open
}

// Reward is one weighted entry of a reward set.
type Reward struct {
	StockID int   `json:"stockId"`
	Weight  int64 `json:"weight"`
	Notice  bool  `json:"notice,omitempty"`  // needToNotice: announced as a premium win
	Summary int   `json:"summary,omitempty"` // position in the 可获得道具 list
}

// RewardSet is a weighted reward table; one reward is drawn from it.
type RewardSet struct {
	ID      int      `json:"id"`
	Rewards []Reward `json:"rewards"`

	total int64
}

// StockItem is one item a stock grants. Days 0 is permanent.
type StockItem struct {
	Category int `json:"category"`
	ItemID   int `json:"itemId"`
	Count    int `json:"count"`
	Days     int `json:"days"`
}

// Key returns the item key.
func (s StockItem) Key() ItemKey { return ItemKey{Category: s.Category, ItemID: s.ItemID} }

// Stock is an original stock.kml row: what a reward or pack grants.
type Stock struct {
	StockID int         `json:"stockId"`
	Name    string      `json:"name,omitempty"` // only for items item.kml does not name
	Items   []StockItem `json:"items"`
}

// Prize is a mileage prize reached at Points uses.
type Prize struct {
	Points  int `json:"points"`
	StockID int `json:"stockId"`
}

// Mileage is a lottery's 保底: every use adds a point, and each prize is
// granted when the points reach it. EventItemID is the lottery's [活动]
// variant, which does not collect points.
type Mileage struct {
	ItemID      int     `json:"itemId"`
	EventItemID int     `json:"eventItemId,omitempty"`
	Prizes      []Prize `json:"prizes"`
}

// HuntReward is one reward of the treasure hunt. Summary places it in one of
// the nine board slots; AcquireCount makes it a 保底 reward granted at the
// latest on that many counted draws.
type HuntReward struct {
	StockID      int  `json:"stockId"`
	Summary      int  `json:"summary,omitempty"`
	AcquireCount int  `json:"acquireCount,omitempty"`
	Effect       bool `json:"effect,omitempty"`
}

// TreasureHunt is a 寻宝 reward set (treasureHunt.xml). Every draw consumes
// one Material or EventMaterial (寻宝放大镜) and one OtherMaterial (幸运藏宝图),
// all category 34.
type TreasureHunt struct {
	ID            int          `json:"id"`
	Theme         string       `json:"theme"`
	Material      int          `json:"material"`
	EventMaterial int          `json:"eventMaterial,omitempty"`
	OtherMaterial int          `json:"otherMaterial"`
	Start         string       `json:"start,omitempty"`
	End           string       `json:"end,omitempty"`
	StockCardID   int          `json:"stockCardId,omitempty"`
	Rewards       []HuntReward `json:"rewards"`

	weights []int64
	total   int64
}

// Pack is an original on-sale stock that sells lottery materials (with
// whatever else the stock bundles).
type Pack struct {
	StockID  int              `json:"stockId"`
	Name     string           `json:"name"`
	Currency economy.Currency `json:"currency"`
	Price    int64            `json:"price"`
	MinExp   int64            `json:"minExp,omitempty"`
}

// ItemInfo is a named item.kml row.
type ItemInfo struct {
	Category int    `json:"category"`
	ItemID   int    `json:"itemId"`
	Name     string `json:"name"`
	Count    bool   `json:"count,omitempty"`  // isAdditional: a stack of a quantity
	Effect   string `json:"effect,omitempty"` // lottery items and materials only
}

// Data is lottery.json. All fields and returned values are shared read-only data.
type Data struct {
	Version       string         `json:"version"`
	GeneratedFrom string         `json:"generatedFrom"`
	Lotteries     []Lottery      `json:"lotteries"`
	RewardSets    []RewardSet    `json:"rewardSets"`
	Mileage       []Mileage      `json:"mileage"`
	TreasureHunts []TreasureHunt `json:"treasureHunts"`
	Packs         []Pack         `json:"packs"`
	Stocks        []Stock        `json:"stocks"`
	Items         []ItemInfo     `json:"items"`

	lotteries map[int]*Lottery
	sets      map[int]*RewardSet
	stocks    map[int]*Stock
	items     map[ItemKey]*ItemInfo
	mileage   map[int]*Mileage
	packs     map[int]*Pack
	// packsByItem lists the packs that contain each item.
	packsByItem map[ItemKey][]*Pack
}

var versionPattern = regexp.MustCompile(`^[0-9a-f]{64}$`)

// Parse decodes and validates a lottery.json document.
func Parse(raw []byte) (*Data, error) {
	d := &Data{}
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(d); err != nil {
		return nil, fmt.Errorf("lottery.json: %w", err)
	}
	if _, err := decoder.Token(); !errors.Is(err, io.EOF) {
		return nil, errors.New("lottery.json: trailing data")
	}
	if err := d.index(); err != nil {
		return nil, fmt.Errorf("lottery.json: %w", err)
	}
	return d, nil
}

var loadDefault = sync.OnceValues(func() (*Data, error) { return Parse(embedded) })

// Default returns the embedded tables, parsed once per process.
func Default() (*Data, error) { return loadDefault() }

func validPeriod(start, end string) error {
	var from, until time.Time
	for _, part := range []struct {
		text   string
		target *time.Time
	}{{start, &from}, {end, &until}} {
		if part.text == "" {
			continue
		}
		at, err := time.Parse(time.RFC3339, part.text)
		if err != nil || !strings.HasSuffix(part.text, "+08:00") {
			return fmt.Errorf("time %q is not ISO 8601 with +08:00", part.text)
		}
		*part.target = at
	}
	if start != "" && end != "" && !from.Before(until) {
		return fmt.Errorf("empty period %s ~ %s", start, end)
	}
	return nil
}

// periodMillis is a validated period as [from, until) Unix ms, 0 when open
// (the end is inclusive to the second, as the original writes it).
func periodMillis(start, end string) (from, until int64) {
	if at, err := time.Parse(time.RFC3339, start); err == nil && start != "" {
		from = at.UnixMilli()
	}
	if at, err := time.Parse(time.RFC3339, end); err == nil && end != "" {
		until = at.Add(time.Second).UnixMilli()
	}
	return from, until
}

func (d *Data) index() error {
	if !versionPattern.MatchString(d.Version) {
		return fmt.Errorf("version %q is not a SHA-256 hex digest", d.Version)
	}
	d.stocks = make(map[int]*Stock, len(d.Stocks))
	for i := range d.Stocks {
		stock := &d.Stocks[i]
		if stock.StockID <= 0 || d.stocks[stock.StockID] != nil || len(stock.Items) == 0 {
			return fmt.Errorf("stock %d: invalid, repeated or empty", stock.StockID)
		}
		for _, item := range stock.Items {
			if item.Category < 0 || item.ItemID < 0 || item.Count < 1 || item.Days < 0 {
				return fmt.Errorf("stock %d: invalid item %+v", stock.StockID, item)
			}
		}
		d.stocks[stock.StockID] = stock
	}
	d.items = make(map[ItemKey]*ItemInfo, len(d.Items))
	for i := range d.Items {
		item := &d.Items[i]
		key := ItemKey{Category: item.Category, ItemID: item.ItemID}
		if item.Name == "" || d.items[key] != nil {
			return fmt.Errorf("item %s: unnamed or repeated", key)
		}
		d.items[key] = item
	}
	d.sets = make(map[int]*RewardSet, len(d.RewardSets))
	for i := range d.RewardSets {
		set := &d.RewardSets[i]
		if set.ID <= 0 || d.sets[set.ID] != nil {
			return fmt.Errorf("reward set %d: invalid or repeated", set.ID)
		}
		for _, reward := range set.Rewards {
			if reward.Weight < 0 || d.stocks[reward.StockID] == nil {
				return fmt.Errorf("reward set %d: reward %+v", set.ID, reward)
			}
			set.total += reward.Weight
		}
		d.sets[set.ID] = set
	}
	d.lotteries = make(map[int]*Lottery, len(d.Lotteries))
	for i := range d.Lotteries {
		lottery := &d.Lotteries[i]
		if lottery.ItemID <= 0 || d.lotteries[lottery.ItemID] != nil || lottery.Name == "" || len(lottery.Sets) == 0 {
			return fmt.Errorf("lottery %d: invalid, repeated, unnamed or without sets", lottery.ItemID)
		}
		if d.items[ItemKey{Category, lottery.ItemID}] == nil {
			return fmt.Errorf("lottery %d: no item %d:%d", lottery.ItemID, Category, lottery.ItemID)
		}
		if lottery.Key != 0 && d.items[ItemKey{Category, lottery.Key}] == nil {
			return fmt.Errorf("lottery %d: no key item %d:%d", lottery.ItemID, Category, lottery.Key)
		}
		for _, id := range lottery.Sets {
			if d.sets[id] == nil {
				return fmt.Errorf("lottery %d: unknown reward set %d", lottery.ItemID, id)
			}
		}
		if err := validPeriod(lottery.Start, lottery.End); err != nil {
			return fmt.Errorf("lottery %d: %w", lottery.ItemID, err)
		}
		lottery.from, lottery.until = periodMillis(lottery.Start, lottery.End)
		d.lotteries[lottery.ItemID] = lottery
	}
	d.mileage = make(map[int]*Mileage, len(d.Mileage))
	for i := range d.Mileage {
		row := &d.Mileage[i]
		if d.lotteries[row.ItemID] == nil || d.mileage[row.ItemID] != nil || len(row.Prizes) == 0 {
			return fmt.Errorf("mileage %d: unknown lottery, repeated or without prizes", row.ItemID)
		}
		last := 0
		for _, prize := range row.Prizes {
			if prize.Points <= last || d.stocks[prize.StockID] == nil {
				return fmt.Errorf("mileage %d: prize %+v", row.ItemID, prize)
			}
			last = prize.Points
		}
		d.mileage[row.ItemID] = row
	}
	if len(d.TreasureHunts) == 0 {
		return errors.New("no treasure hunt")
	}
	for i := range d.TreasureHunts {
		if err := d.TreasureHunts[i].prepare(d); err != nil {
			return fmt.Errorf("treasure hunt %d: %w", d.TreasureHunts[i].ID, err)
		}
	}
	d.packs = make(map[int]*Pack, len(d.Packs))
	d.packsByItem = map[ItemKey][]*Pack{}
	for i := range d.Packs {
		pack := &d.Packs[i]
		stock := d.stocks[pack.StockID]
		if stock == nil || d.packs[pack.StockID] != nil || !pack.Currency.Valid() || pack.Price < 1 ||
			pack.MinExp < 0 || pack.Name == "" {
			return fmt.Errorf("pack %d: invalid", pack.StockID)
		}
		d.packs[pack.StockID] = pack
		seen := map[ItemKey]bool{}
		for _, item := range stock.Items {
			if !seen[item.Key()] {
				seen[item.Key()] = true
				d.packsByItem[item.Key()] = append(d.packsByItem[item.Key()], pack)
			}
		}
	}
	return nil
}

// Lottery returns the lottery of a category-24 item.
func (d *Data) Lottery(itemID int) (*Lottery, bool) {
	lottery, ok := d.lotteries[itemID]
	return lottery, ok
}

// Set returns a reward set.
func (d *Data) Set(id int) (*RewardSet, bool) {
	set, ok := d.sets[id]
	return set, ok
}

// StockByID returns a stock.
func (d *Data) StockByID(id int) (*Stock, bool) {
	stock, ok := d.stocks[id]
	return stock, ok
}

// Info returns an item's item.kml row.
func (d *Data) Info(key ItemKey) (*ItemInfo, bool) {
	item, ok := d.items[key]
	return item, ok
}

// IsCountItem reports whether an item is a stack (isAdditional). Items
// item.kml does not describe (a few category 63-66 rewards) are stacks too.
func (d *Data) IsCountItem(key ItemKey) bool {
	item, ok := d.items[key]
	return !ok || item.Count
}

// ItemName returns an item's name, or the stock name for the unnamed ones.
func (d *Data) ItemName(key ItemKey, stock *Stock) string {
	if item, ok := d.items[key]; ok {
		return item.Name
	}
	if stock != nil {
		return stock.Name
	}
	return ""
}

// MileageOf returns the mileage of a lottery: its own, or the one it is
// the [活动] variant of (event reports the latter; it collects no points).
func (d *Data) MileageOf(itemID int) (mileage *Mileage, event bool, ok bool) {
	if row, found := d.mileage[itemID]; found {
		return row, false, true
	}
	for i := range d.Mileage {
		if d.Mileage[i].EventItemID == itemID {
			return &d.Mileage[i], true, true
		}
	}
	return nil, false, false
}

// TreasureHunt returns the current treasure-hunt table: the latest one.
func (d *Data) TreasureHunt() *TreasureHunt {
	latest := &d.TreasureHunts[0]
	for i := range d.TreasureHunts {
		if d.TreasureHunts[i].ID > latest.ID {
			latest = &d.TreasureHunts[i]
		}
	}
	return latest
}

// Pack returns an on-sale pack.
func (d *Data) Pack(stockID int) (*Pack, bool) {
	pack, ok := d.packs[stockID]
	return pack, ok
}

// PacksWith lists the packs that contain any of keys, by stock id. Only
// packs of the key items alone count for keys in only (幸运车胎 by the
// hundred, not every old bundle that also gave some).
func (d *Data) PacksWith(keys []ItemKey, only []ItemKey) []*Pack {
	seen := map[int]bool{}
	var packs []*Pack
	add := func(pack *Pack) {
		if !seen[pack.StockID] {
			seen[pack.StockID] = true
			packs = append(packs, pack)
		}
	}
	for _, key := range keys {
		for _, pack := range d.packsByItem[key] {
			add(pack)
		}
	}
	for _, key := range only {
		for _, pack := range d.packsByItem[key] {
			if stock := d.stocks[pack.StockID]; !slices.ContainsFunc(stock.Items, func(item StockItem) bool {
				return !slices.Contains(only, item.Key())
			}) {
				add(pack)
			}
		}
	}
	sort.Slice(packs, func(i, j int) bool { return packs[i].StockID < packs[j].StockID })
	return packs
}

// LotteryPacks lists the packs that sell a lottery: packs with the lottery
// item, and packs made only of its key item.
func (d *Data) LotteryPacks(lottery *Lottery) []*Pack {
	var only []ItemKey
	if lottery.Key != 0 {
		only = []ItemKey{{Category, lottery.Key}}
	}
	return d.PacksWith([]ItemKey{{Category, lottery.ItemID}}, only)
}

// HuntPacks lists the packs that sell the treasure-hunt materials.
func (d *Data) HuntPacks(hunt *TreasureHunt) []*Pack {
	keys := []ItemKey{{MaterialCategory, hunt.Material}, {MaterialCategory, hunt.OtherMaterial}}
	if hunt.EventMaterial != 0 {
		keys = append(keys, ItemKey{MaterialCategory, hunt.EventMaterial})
	}
	return d.PacksWith(keys, nil)
}

// FeaturedLotteries lists the lotteries an original on-sale pack sells, by item id.
func (d *Data) FeaturedLotteries() []*Lottery {
	var featured []*Lottery
	for i := range d.Lotteries {
		lottery := &d.Lotteries[i]
		if len(d.packsByItem[ItemKey{Category, lottery.ItemID}]) > 0 {
			featured = append(featured, lottery)
		}
	}
	return featured
}

/* ---------- the 我的物品 box opening (store OpenBox) ---------- */

// Item is one item of a reward stock, as the box opening names it.
type Item = StockItem

// Stock returns the items of a stock (nil when unknown).
func (d *Data) Stock(id int) []Item {
	if stock, ok := d.stocks[id]; ok {
		return stock.Items
	}
	return nil
}

// Name is an item's CN name ("" when item.kml has none).
func (d *Data) Name(category, itemID int) string {
	if item, ok := d.items[ItemKey{Category: category, ItemID: itemID}]; ok {
		return item.Name
	}
	return ""
}

// Rewards are the weighted rewards the box opening draws one from at now
// (Unix ms): every reward of the lottery's sets while its original period
// runs, nil outside it. (The 精品道具场 instead draws one reward from each
// set and ignores the original period: store Gacha.)
func (d *Data) Rewards(l *Lottery, now int64) []Reward {
	if (l.from != 0 && now < l.from) || (l.until != 0 && now >= l.until) {
		return nil
	}
	var rewards []Reward
	for _, id := range l.Sets {
		rewards = append(rewards, d.sets[id].Rewards...)
	}
	return rewards
}

// Draw picks a reward by weight; roll returns a uniform integer in [0, n).
// It returns false when the rewards weigh nothing.
func Draw(rewards []Reward, roll func(n int) int) (Reward, bool) {
	var total int64
	for _, reward := range rewards {
		total += reward.Weight
	}
	if total <= 0 {
		return Reward{}, false
	}
	pick := int64(roll(int(total)))
	for _, reward := range rewards {
		if pick < reward.Weight {
			return reward, true
		}
		pick -= reward.Weight
	}
	return rewards[len(rewards)-1], true
}
