/* Automatically generated by wasm2c */
#ifndef MOTOR_VORBIS_H_GENERATED_
#define MOTOR_VORBIS_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_wasi__snapshot__preview1;

typedef struct w2c_motorvorbis {
  struct w2c_wasi__snapshot__preview1* w2c_wasi__snapshot__preview1_instance;
  u32 w2c_0x5F_stack_pointer;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_motorvorbis;

void wasm2c_motorvorbis_instantiate(w2c_motorvorbis*, struct w2c_wasi__snapshot__preview1*);
void wasm2c_motorvorbis_free(w2c_motorvorbis*);
wasm_rt_func_type_t wasm2c_motorvorbis_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'wasi_snapshot_preview1' 'fd_prestat_dir_name' */
u32 w2c_wasi__snapshot__preview1_fd_prestat_dir_name(struct w2c_wasi__snapshot__preview1*, u32, u32, u32);
void wasm_tailcall_w2c_wasi__snapshot__preview1_fd_prestat_dir_name(void **instance_ptr, void *tail_call_stack, wasm_rt_tailcallee_t *next);

/* import: 'wasi_snapshot_preview1' 'fd_prestat_get' */
u32 w2c_wasi__snapshot__preview1_fd_prestat_get(struct w2c_wasi__snapshot__preview1*, u32, u32);
void wasm_tailcall_w2c_wasi__snapshot__preview1_fd_prestat_get(void **instance_ptr, void *tail_call_stack, wasm_rt_tailcallee_t *next);

/* import: 'wasi_snapshot_preview1' 'proc_exit' */
void w2c_wasi__snapshot__preview1_proc_exit(struct w2c_wasi__snapshot__preview1*, u32);
void wasm_tailcall_w2c_wasi__snapshot__preview1_proc_exit(void **instance_ptr, void *tail_call_stack, wasm_rt_tailcallee_t *next);

/* import: 'wasi_snapshot_preview1' 'random_get' */
u32 w2c_wasi__snapshot__preview1_random_get(struct w2c_wasi__snapshot__preview1*, u32, u32);
void wasm_tailcall_w2c_wasi__snapshot__preview1_random_get(void **instance_ptr, void *tail_call_stack, wasm_rt_tailcallee_t *next);

/* export: 'memory' */
wasm_rt_memory_t* w2c_motorvorbis_memory(w2c_motorvorbis* instance);

/* export: '_initialize' */
void w2c_motorvorbis_0x5Finitialize(w2c_motorvorbis*);

/* export: 'malloc' */
u32 w2c_motorvorbis_malloc(w2c_motorvorbis*, u32);

/* export: 'free' */
void w2c_motorvorbis_free(w2c_motorvorbis*, u32);

/* export: 'decode' */
u32 w2c_motorvorbis_decode(w2c_motorvorbis*, u32, u32);

/* export: 'release' */
void w2c_motorvorbis_release(w2c_motorvorbis*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* MOTOR_VORBIS_H_GENERATED_ */
