package anticheat

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

// tracks.json is generated by rewrite/tools/export-track-data.mjs from the
// p3553 track metadata and routes.
//
//go:embed tracks.json
var tracksJSON []byte

// Track is what the checks know about one p3553 track (ANTICHEAT.md 2).
type Track struct {
	ID   string `json:"id"`
	Laps int    `json:"laps"`
	// Lap is the shortest route from the first section through the last
	// (m): the route distance a lap adds at the least; Drive the same with
	// warp sections as 0 m, the distance a kart drives at the least. Both
	// are 0 when the route has no such path.
	Lap   float64 `json:"lap"`
	Drive float64 `json:"drive"`
	// Jump is the longest section (m): the most route distance a warp, a
	// shortcut over a section or a rail landing adds at once.
	Jump float64 `json:"jump"`
	// Warp is the length of all the track's warp sections (m): the most
	// route distance warps add in a lap without driving (0: no warps).
	Warp float64 `json:"warp"`
	// Warps are where the track's warps put a kart, in the wire
	// coordinates of motion frames ([x, -z, y], meters).
	Warps [][3]float64 `json:"warps"`
}

var tracks = func() map[string]*Track {
	var document struct {
		Tracks []*Track `json:"tracks"`
	}
	if err := json.Unmarshal(tracksJSON, &document); err != nil {
		panic(fmt.Sprintf("anticheat: tracks.json: %v", err))
	}
	byID := make(map[string]*Track, len(document.Tracks))
	for _, track := range document.Tracks {
		if track.ID == "" || track.Laps < 1 || track.Jump <= 0 {
			panic(fmt.Sprintf("anticheat: tracks.json: bad row %+v", *track))
		}
		byID[track.ID] = track
	}
	return byID
}()

// TrackByID returns the p3553 track id, or nil for an unknown one.
func TrackByID(id string) *Track { return tracks[id] }
