// Package itemmode holds the rules of the item races (道具个人赛 / 组队道具赛,
// rewrite/ITEM_MODE.md) that the game node enforces: the original
// rank-group probability tables and per-race caps, item slots, target
// selection, item timelines, slot locks, scans and the cube anti-abuse
// check. It is pure: callers pass the time, the standings and the random
// source, and turn the results into protocol events.
//
// itemmode.json is generated by rewrite/tools/export-item-mode-data.mjs and
// embedded here; never edit it by hand (version_test.go recomputes its
// content version).
package itemmode

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"regexp"
	"slices"
	"sync"
)

//go:embed itemmode.json
var embedded []byte

// Table kinds: 道具个人赛 draws from itemProb_indi@zz, 组队道具赛 from
// itemProb_team2@cn.
const (
	TableIndividual = "indi"
	TableTeam       = "team"
)

// Entry is one row of a probability table: an item and its weight in each
// rank group.
type Entry struct {
	Idx  int    `json:"idx"`
	Name string `json:"name"`
	Top  int    `json:"top"`
	High int    `json:"high"`
	Mid  int    `json:"mid"`
	Low  int    `json:"low"`
}

// Weight returns the entry's weight in group.
func (e Entry) Weight(group Group) int {
	switch group {
	case GroupTop:
		return e.Top
	case GroupHigh:
		return e.High
	case GroupMid:
		return e.Mid
	}
	return e.Low
}

// Table is an original itemProb table.
type Table struct {
	Source  string  `json:"source"`
	Entries []Entry `json:"items"`
}

// Contains reports whether the table can grant idx.
func (t *Table) Contains(idx int) bool {
	return slices.ContainsFunc(t.Entries, func(e Entry) bool { return e.Idx == idx })
}

// Item is one table item with the lifetimes (ms) of its base-0 item.bml
// states; booster has none (its time is the kart's itemBoosterTime).
type Item struct {
	Idx    int            `json:"idx"`
	Name   string         `json:"name"`
	Folder string         `json:"folder,omitempty"` // item.rho folder when it is not Name
	States map[string]int `json:"states"`
}

// Life returns the lifetime of a base-0 state, 0 when it has none.
func (i Item) Life(state string) int { return i.States[state] }

// Track is a track item rooms accept: an item track whose model holds item
// cubes (Cubes counts static and moving ones in that exact model).
type Track struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Cubes    int    `json:"cubes"`
	OnlyItem bool   `json:"onlyItem,omitempty"` // isOnlyItemTrack
	Reverse  bool   `json:"reverse,omitempty"`
}

// Pool is the track pool of a random-track code in an item room.
type Pool struct {
	Code   int      `json:"code"`
	Group  string   `json:"group"` // the client random group it mirrors
	Tracks []string `json:"tracks"`
}

// Cap limits how many times a racer can get an item in one race
// (itemGameRestrictionItemCount.xml targetItemList).
type Cap struct {
	Idx        int    `json:"idx"`
	Name       string `json:"name"`
	AllowCount int    `json:"allowCount"`
}

// Data is the parsed itemmode.json.
type Data struct {
	Version       string            `json:"version"`
	GeneratedFrom string            `json:"generatedFrom"`
	Tables        map[string]*Table `json:"tables"`
	Restrictions  struct {
		Caps []Cap `json:"caps"`
		// Unlimited are the disableItemList items, read as exempt from the
		// restriction (ITEM_MODE.md 4).
		Unlimited []struct {
			Idx  int    `json:"idx"`
			Name string `json:"name"`
		} `json:"unlimited"`
	} `json:"restrictions"`
	Items        []Item  `json:"items"`
	Tracks       []Track `json:"tracks"`
	RandomPools  []Pool  `json:"randomPools"`
	DefaultTrack string  `json:"defaultTrack"`

	items  map[int]Item
	caps   map[int]int
	tracks map[string]Track
	pools  map[int][]string
}

// RandomCodes are the random-track codes an item room accepts (the
// client's codes for hot1-hot5, all, new and reverse; 40, speed only, is
// not one of them).
var RandomCodes = []int{0, 3, 4, 5, 6, 7, 8, 30}

var trackIDPattern = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_]{0,63}$`)

// Parse decodes and checks itemmode.json.
func Parse(data []byte) (*Data, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var d Data
	if err := decoder.Decode(&d); err != nil {
		return nil, fmt.Errorf("itemmode.json: %w", err)
	}
	if _, err := decoder.Token(); !errors.Is(err, io.EOF) {
		return nil, errors.New("itemmode.json: trailing data")
	}
	if err := d.index(); err != nil {
		return nil, fmt.Errorf("itemmode.json: %w", err)
	}
	return &d, nil
}

func (d *Data) index() error {
	if d.Version == "" {
		return errors.New("no version")
	}
	d.items = make(map[int]Item, len(d.Items))
	for _, item := range d.Items {
		if _, dup := d.items[item.Idx]; dup {
			return fmt.Errorf("item %d listed twice", item.Idx)
		}
		for state, life := range item.States {
			if life < 0 {
				return fmt.Errorf("item %s state %s life %d", item.Name, state, life)
			}
		}
		d.items[item.Idx] = item
	}
	for _, kind := range []string{TableIndividual, TableTeam} {
		table := d.Tables[kind]
		if table == nil || len(table.Entries) == 0 {
			return fmt.Errorf("table %s missing", kind)
		}
		seen := map[int]bool{}
		for _, entry := range table.Entries {
			if seen[entry.Idx] {
				return fmt.Errorf("table %s lists %d twice", kind, entry.Idx)
			}
			seen[entry.Idx] = true
			if entry.Top < 0 || entry.High < 0 || entry.Mid < 0 || entry.Low < 0 {
				return fmt.Errorf("table %s: negative weight for %s", kind, entry.Name)
			}
			item, ok := d.items[entry.Idx]
			if !ok || item.Name != entry.Name {
				return fmt.Errorf("table %s: %s (%d) has no item row", kind, entry.Name, entry.Idx)
			}
			if _, ok := rules[entry.Idx]; !ok {
				return fmt.Errorf("table %s: no rule for %s (%d)", kind, entry.Name, entry.Idx)
			}
		}
		for _, group := range []Group{GroupTop, GroupHigh, GroupMid, GroupLow} {
			total := 0
			for _, entry := range table.Entries {
				total += entry.Weight(group)
			}
			if total <= 0 {
				return fmt.Errorf("table %s: no weight in group %s", kind, group)
			}
		}
	}
	for idx, states := range requiredStates {
		item, ok := d.items[idx]
		if !ok {
			return fmt.Errorf("item %d missing", idx)
		}
		for _, state := range states {
			if _, ok := item.States[state]; !ok {
				return fmt.Errorf("item %s has no %s state", item.Name, state)
			}
		}
	}
	d.caps = map[int]int{}
	for _, c := range d.Restrictions.Caps {
		if _, ok := d.items[c.Idx]; !ok || c.AllowCount < 1 {
			return fmt.Errorf("cap %s (%d) invalid", c.Name, c.Idx)
		}
		d.caps[c.Idx] = c.AllowCount
	}
	for _, u := range d.Restrictions.Unlimited {
		if _, capped := d.caps[u.Idx]; capped {
			return fmt.Errorf("item %s is capped and unlimited", u.Name)
		}
	}
	d.tracks = make(map[string]Track, len(d.Tracks))
	for _, track := range d.Tracks {
		if !trackIDPattern.MatchString(track.ID) || track.Cubes <= 0 {
			return fmt.Errorf("track %q invalid", track.ID)
		}
		if _, dup := d.tracks[track.ID]; dup {
			return fmt.Errorf("track %s listed twice", track.ID)
		}
		d.tracks[track.ID] = track
	}
	d.pools = map[int][]string{}
	for _, pool := range d.RandomPools {
		if !slices.Contains(RandomCodes, pool.Code) || len(pool.Tracks) == 0 {
			return fmt.Errorf("random pool %d invalid", pool.Code)
		}
		if _, dup := d.pools[pool.Code]; dup {
			return fmt.Errorf("random pool %d listed twice", pool.Code)
		}
		for _, id := range pool.Tracks {
			if _, ok := d.tracks[id]; !ok {
				return fmt.Errorf("random pool %d: unknown track %s", pool.Code, id)
			}
		}
		d.pools[pool.Code] = pool.Tracks
	}
	for _, code := range RandomCodes {
		if _, ok := d.pools[code]; !ok {
			return fmt.Errorf("random pool %d missing", code)
		}
	}
	if _, ok := d.tracks[d.DefaultTrack]; !ok {
		return fmt.Errorf("default track %q unknown", d.DefaultTrack)
	}
	return nil
}

// requiredStates are the base-0 states the server timelines read.
var requiredStates = map[int][]string{
	WaterFly:    {"Use"},
	Rocket:      {"Use"},
	UFO:         {"Use"},
	SlotLock:    {"Use", "Affect", "Postaffect"},
	Scanning:    {"Affect"},
	Angel:       {"Affect"},
	Shield:      {"Use"},
	TimeBomb:    {"Use"},
	Barricade:   {"StateUse"},
	WaterBomb:   {"Use"},
	Banana:      {"Use", "Set"},
	Devil:       {"Use", "Preaffect", "Affect"},
	Thunderbolt: {"Use", "Warning", "Preaffect", "Affect"},
	Cloud:       {"Use", "Set"},
	EMP:         {"Affect"},
	Magnet:      {"Use"},
}

// Table returns the probability table of kind (TableIndividual, TableTeam).
func (d *Data) Table(kind string) *Table { return d.Tables[kind] }

// Item returns a table item.
func (d *Data) Item(idx int) (Item, bool) {
	item, ok := d.items[idx]
	return item, ok
}

// Cap returns how many times a racer can get idx in one race; ok is false
// for an item the restriction does not limit.
func (d *Data) Cap(idx int) (allowCount int, ok bool) {
	allowCount, ok = d.caps[idx]
	return allowCount, ok
}

// Track returns an item room track.
func (d *Data) Track(id string) (Track, bool) {
	track, ok := d.tracks[id]
	return track, ok
}

// Pool returns the tracks of a random-track code (nil for a code item rooms
// do not accept).
func (d *Data) Pool(code int) []string { return d.pools[code] }

var loadDefault = sync.OnceValues(func() (*Data, error) { return Parse(embedded) })

// Default returns the embedded data, parsed once.
func Default() (*Data, error) { return loadDefault() }
