// Package itemmode holds the rules of the item races (道具个人赛 / 组队道具赛,
// rewrite/ITEM_MODE.md) that the game node enforces: the original
// rank-group probability tables and per-race caps, item slots, target
// selection, item timelines, slot locks, scans and the cube anti-abuse
// check, and (appendix C) the per-kart item tables, the special items they
// lead to, the equipment passives a victim may claim, the item changer
// cards, the in-race lucci and the result titles. It is pure: callers pass
// the time, the standings and the random source, and turn the results into
// protocol events.
//
// itemmode.json is generated by rewrite/tools/export-item-mode-data.mjs and
// embedded here; never edit it by hand (version_test.go recomputes its
// content version).
package itemmode

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"regexp"
	"slices"
	"strconv"
	"sync"
)

//go:embed itemmode.json
var embedded []byte

// Table kinds: 道具个人赛 draws from itemProb_indi@zz, 组队道具赛 from
// itemProb_team2@cn; their 道具变更卡 (item changer) redraws from
// itemProb_indiChanger@zz and itemProb_teamChanger2@cn.
const (
	TableIndividual  = "indi"
	TableTeam        = "team"
	TableIndiChanger = "indiChanger"
	TableTeamChanger = "teamChanger"
)

// changerTable is the item changer table of a race table.
var changerTable = map[string]string{TableIndividual: TableIndiChanger, TableTeam: TableTeamChanger}

// Entry is one row of a probability table: an item and its weight in each
// rank group.
type Entry struct {
	Idx  int    `json:"idx"`
	Name string `json:"name"`
	Top  int    `json:"top"`
	High int    `json:"high"`
	Mid  int    `json:"mid"`
	Low  int    `json:"low"`
}

// Weight returns the entry's weight in group.
func (e Entry) Weight(group Group) int {
	switch group {
	case GroupTop:
		return e.Top
	case GroupHigh:
		return e.High
	case GroupMid:
		return e.Mid
	}
	return e.Low
}

// Table is an original itemProb table.
type Table struct {
	Source  string  `json:"source"`
	Entries []Entry `json:"items"`
}

// Contains reports whether the table can grant idx.
func (t *Table) Contains(idx int) bool {
	return slices.ContainsFunc(t.Entries, func(e Entry) bool { return e.Idx == idx })
}

// Item is one race item with the lifetimes (ms) of the item.bml states of
// its variant (Base, 0 for the table items); booster and the special
// booster have none (their times are the kart's).
type Item struct {
	Idx    int            `json:"idx"`
	Name   string         `json:"name"`
	Folder string         `json:"folder,omitempty"` // item.rho folder when it is not Name
	Base   int            `json:"base,omitempty"`   // the variant within the folder's item.bml
	States map[string]int `json:"states"`
}

// Life returns the lifetime of a state of the item's variant, 0 when it has none.
func (i Item) Life(state string) int { return i.States[state] }

// Track is a track item rooms accept: an item track whose model holds item
// cubes (Cubes counts static and moving ones in that exact model).
type Track struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Cubes    int    `json:"cubes"`
	OnlyItem bool   `json:"onlyItem,omitempty"` // isOnlyItemTrack
	Reverse  bool   `json:"reverse,omitempty"`
	// Level is the track@zz level (0 when unset), which transform@zz keys on.
	Level int `json:"level"`
}

// Pool is the track pool of a random-track code in an item room.
type Pool struct {
	Code   int      `json:"code"`
	Group  string   `json:"group"` // the client random group it mirrors
	Tracks []string `json:"tracks"`
}

// Cap limits how many times a racer can get an item in one race
// (itemGameRestrictionItemCount.xml targetItemList).
type Cap struct {
	Idx        int    `json:"idx"`
	Name       string `json:"name"`
	AllowCount int    `json:"allowCount"`
}

// KartTransform is a transformByKart row: an item Src the kart gets from a
// cube becomes Dst with probability P (percent).
type KartTransform struct {
	Kart int `json:"kart"`
	Src  int `json:"src"`
	Dst  int `json:"dst"`
	P    int `json:"p"`
}

// KartGain is a fired2Gain row (the kart is hit by Item) or a firing2Gain
// row (the kart uses Item): it gains Gain with probability P.
type KartGain struct {
	Kart int `json:"kart"`
	Item int `json:"item"`
	Gain int `json:"gain"`
	P    int `json:"p"`
}

// AnimalBooster is an animalBooster row: a booster the kart gets becomes the
// special booster (AnimalBooster) with probability P, shown with the slot
// icon item/slot/animal<Icon>.png (0: the plain special booster icon).
type AnimalBooster struct {
	Kart int `json:"kart"`
	Icon int `json:"icon"`
	P    int `json:"p"`
}

// KartTables are the merged per-kart item tables (ITEM_MODE.md C.3).
type KartTables struct {
	Transform     []KartTransform `json:"transform"`
	Fired         []KartGain      `json:"fired"`
	Firing        []KartGain      `json:"firing"`
	AnimalBooster []AnimalBooster `json:"animalBooster"`
}

// TrackTransform is a transform@zz row: a drawn Src becomes Dst on tracks
// of Level (reverse tracks only when Reverse) with probability P.
type TrackTransform struct {
	Src     int  `json:"src"`
	Dst     int  `json:"dst"`
	Level   int  `json:"level"`
	Reverse bool `json:"reverse,omitempty"`
	P       int  `json:"p"`
}

// EnchantShield is one enchantCatalog.xml Tune's EnchanterShield items (the
// item-race ones): what a passive key defends against.
type EnchantShield struct {
	Group int      `json:"group"`
	Tune  int      `json:"tune"`
	Key   string   `json:"key,omitempty"`
	Items []int    `json:"items"`
	Names []string `json:"names"`
}

// Title is one result title of title_icons/namemap@zz: Fail (perfectAim),
// Item/Items/Use (used one of Items at least Use times), or Custom 1..3.
type Title struct {
	Key    string `json:"key"`
	Name   string `json:"name"`
	Fail   *int   `json:"fail,omitempty"`
	Item   string `json:"item,omitempty"`
	Items  []int  `json:"items,omitempty"`
	Use    int    `json:"use,omitempty"`
	Custom int    `json:"custom,omitempty"`
}

// Data is the parsed itemmode.json.
type Data struct {
	Version       string            `json:"version"`
	GeneratedFrom string            `json:"generatedFrom"`
	Tables        map[string]*Table `json:"tables"`
	Restrictions  struct {
		Caps []Cap `json:"caps"`
		// Unlimited are the disableItemList items, read as exempt from the
		// restriction (ITEM_MODE.md 4).
		Unlimited []struct {
			Idx  int    `json:"idx"`
			Name string `json:"name"`
		} `json:"unlimited"`
	} `json:"restrictions"`
	Items        []Item  `json:"items"`
	Tracks       []Track `json:"tracks"`
	RandomPools  []Pool  `json:"randomPools"`
	DefaultTrack string  `json:"defaultTrack"`

	KartTables      KartTables       `json:"kartTables"`
	TrackTransforms []TrackTransform `json:"trackTransforms"`
	// Passives are the item-race chances (percent) of the equipment
	// passives by holder (kart, pet, character, balloon, headBand), item id
	// and attribute (ITEM_MODE.md C.2).
	Passives    map[string]map[string]map[string]int `json:"passives"`
	EnchantKeys []EnchantShield                      `json:"enchantKeys"`
	// XunKarts are the 迅 item karts that start a race holding one item.
	XunKarts []int   `json:"xunKarts"`
	Titles   []Title `json:"titles"`

	items     map[int]Item
	caps      map[int]int
	tracks    map[string]Track
	pools     map[int][]string
	transform map[[2]int]KartTransform
	fired     map[[2]int]KartGain
	firing    map[[2]int]KartGain
	animal    map[int]AnimalBooster
	passives  map[string]map[int]map[string]int
	xun       map[int]bool
}

// RandomCodes are the random-track codes an item room accepts (the
// client's codes for hot1-hot5, all, new and reverse; 40, speed only, is
// not one of them).
var RandomCodes = []int{0, 3, 4, 5, 6, 7, 8, 30}

var trackIDPattern = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_]{0,63}$`)

// Parse decodes and checks itemmode.json.
func Parse(data []byte) (*Data, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var d Data
	if err := decoder.Decode(&d); err != nil {
		return nil, fmt.Errorf("itemmode.json: %w", err)
	}
	if _, err := decoder.Token(); !errors.Is(err, io.EOF) {
		return nil, errors.New("itemmode.json: trailing data")
	}
	if err := d.index(); err != nil {
		return nil, fmt.Errorf("itemmode.json: %w", err)
	}
	return &d, nil
}

func (d *Data) index() error {
	if d.Version == "" {
		return errors.New("no version")
	}
	d.items = make(map[int]Item, len(d.Items))
	for _, item := range d.Items {
		if _, dup := d.items[item.Idx]; dup {
			return fmt.Errorf("item %d listed twice", item.Idx)
		}
		for state, life := range item.States {
			if life < 0 {
				return fmt.Errorf("item %s state %s life %d", item.Name, state, life)
			}
		}
		d.items[item.Idx] = item
	}
	for _, kind := range []string{TableIndividual, TableTeam, TableIndiChanger, TableTeamChanger} {
		table := d.Tables[kind]
		if table == nil || len(table.Entries) == 0 {
			return fmt.Errorf("table %s missing", kind)
		}
		seen := map[int]bool{}
		for _, entry := range table.Entries {
			if seen[entry.Idx] {
				return fmt.Errorf("table %s lists %d twice", kind, entry.Idx)
			}
			seen[entry.Idx] = true
			if entry.Top < 0 || entry.High < 0 || entry.Mid < 0 || entry.Low < 0 {
				return fmt.Errorf("table %s: negative weight for %s", kind, entry.Name)
			}
			if entry.Top+entry.High+entry.Mid+entry.Low == 0 && (kind == TableIndiChanger || kind == TableTeamChanger) {
				// A changer row with no weight (oil, rainbowCloud2) is never drawn.
				continue
			}
			item, ok := d.items[entry.Idx]
			if !ok || item.Name != entry.Name {
				return fmt.Errorf("table %s: %s (%d) has no item row", kind, entry.Name, entry.Idx)
			}
			if _, ok := rules[entry.Idx]; !ok {
				return fmt.Errorf("table %s: no rule for %s (%d)", kind, entry.Name, entry.Idx)
			}
		}
		for _, group := range []Group{GroupTop, GroupHigh, GroupMid, GroupLow} {
			total := 0
			for _, entry := range table.Entries {
				total += entry.Weight(group)
			}
			if total <= 0 {
				return fmt.Errorf("table %s: no weight in group %s", kind, group)
			}
		}
	}
	for idx, states := range requiredStates {
		item, ok := d.items[idx]
		if !ok {
			return fmt.Errorf("item %d missing", idx)
		}
		for _, state := range states {
			if _, ok := item.States[state]; !ok {
				return fmt.Errorf("item %s has no %s state", item.Name, state)
			}
		}
	}
	d.caps = map[int]int{}
	for _, c := range d.Restrictions.Caps {
		if _, ok := d.items[c.Idx]; !ok || c.AllowCount < 1 {
			return fmt.Errorf("cap %s (%d) invalid", c.Name, c.Idx)
		}
		d.caps[c.Idx] = c.AllowCount
	}
	for _, u := range d.Restrictions.Unlimited {
		if _, capped := d.caps[u.Idx]; capped {
			return fmt.Errorf("item %s is capped and unlimited", u.Name)
		}
	}
	d.tracks = make(map[string]Track, len(d.Tracks))
	for _, track := range d.Tracks {
		if !trackIDPattern.MatchString(track.ID) || track.Cubes <= 0 {
			return fmt.Errorf("track %q invalid", track.ID)
		}
		if _, dup := d.tracks[track.ID]; dup {
			return fmt.Errorf("track %s listed twice", track.ID)
		}
		d.tracks[track.ID] = track
	}
	d.pools = map[int][]string{}
	for _, pool := range d.RandomPools {
		if !slices.Contains(RandomCodes, pool.Code) || len(pool.Tracks) == 0 {
			return fmt.Errorf("random pool %d invalid", pool.Code)
		}
		if _, dup := d.pools[pool.Code]; dup {
			return fmt.Errorf("random pool %d listed twice", pool.Code)
		}
		for _, id := range pool.Tracks {
			if _, ok := d.tracks[id]; !ok {
				return fmt.Errorf("random pool %d: unknown track %s", pool.Code, id)
			}
		}
		d.pools[pool.Code] = pool.Tracks
	}
	for _, code := range RandomCodes {
		if _, ok := d.pools[code]; !ok {
			return fmt.Errorf("random pool %d missing", code)
		}
	}
	if _, ok := d.tracks[d.DefaultTrack]; !ok {
		return fmt.Errorf("default track %q unknown", d.DefaultTrack)
	}
	return d.indexPhase3()
}

// raceItem reports whether idx is an item a race can hold (an item row
// with a rule).
func (d *Data) raceItem(idx int) bool {
	_, item := d.items[idx]
	_, rule := rules[idx]
	return item && rule
}

func validChance(p int) bool { return p >= 1 && p <= 100 }

// indexPhase3 checks and indexes the appendix C data.
func (d *Data) indexPhase3() error {
	d.transform = map[[2]int]KartTransform{}
	for _, row := range d.KartTables.Transform {
		key := [2]int{row.Kart, row.Src}
		if _, dup := d.transform[key]; dup || row.Kart <= 0 || !validChance(row.P) ||
			!d.raceItem(row.Src) || !d.raceItem(row.Dst) {
			return fmt.Errorf("transformByKart row %+v invalid", row)
		}
		d.transform[key] = row
	}
	gains := func(name string, rows []KartGain) (map[[2]int]KartGain, error) {
		index := map[[2]int]KartGain{}
		for _, row := range rows {
			key := [2]int{row.Kart, row.Item}
			if _, dup := index[key]; dup || row.Kart <= 0 || !validChance(row.P) ||
				!d.raceItem(row.Item) || !d.raceItem(row.Gain) {
				return nil, fmt.Errorf("%s row %+v invalid", name, row)
			}
			index[key] = row
		}
		return index, nil
	}
	var err error
	if d.fired, err = gains("fired2Gain", d.KartTables.Fired); err != nil {
		return err
	}
	if d.firing, err = gains("firing2Gain", d.KartTables.Firing); err != nil {
		return err
	}
	d.animal = map[int]AnimalBooster{}
	for _, row := range d.KartTables.AnimalBooster {
		if _, dup := d.animal[row.Kart]; dup || row.Kart <= 0 || row.Icon < 0 || !validChance(row.P) {
			return fmt.Errorf("animalBooster row %+v invalid", row)
		}
		d.animal[row.Kart] = row
	}
	// Every rule has its item, and the states its timeline reads.
	for idx, rule := range rules {
		item, ok := d.items[idx]
		if !ok {
			return fmt.Errorf("item %d has a rule but no item row", idx)
		}
		if rule.speed > 0 {
			eta := item
			if rule.etaItem != 0 {
				eta = d.items[rule.etaItem]
			}
			if _, ok := eta.States[rule.etaState]; !ok {
				return fmt.Errorf("item %s has no %s state for its eta", item.Name, rule.etaState)
			}
		}
		if rule.lock != nil {
			for _, state := range []string{"Affect", rule.lock.state} {
				if _, ok := item.States[state]; state != "" && !ok {
					return fmt.Errorf("item %s has no %s state for its lock", item.Name, state)
				}
			}
		}
	}
	for _, row := range d.TrackTransforms {
		if row.Level < 0 || !validChance(row.P) || !d.raceItem(row.Src) || !d.raceItem(row.Dst) {
			return fmt.Errorf("transform@zz row %+v invalid", row)
		}
	}
	d.passives = map[string]map[int]map[string]int{}
	for _, holder := range []string{HolderKart, HolderPet, HolderCharacter, HolderBalloon, HolderHeadBand} {
		rows, ok := d.Passives[holder]
		if !ok {
			return fmt.Errorf("passives of %s missing", holder)
		}
		byID := make(map[int]map[string]int, len(rows))
		for id, values := range rows {
			itemID, err := strconv.Atoi(id)
			if err != nil || itemID <= 0 || strconv.Itoa(itemID) != id {
				return fmt.Errorf("passives %s id %q invalid", holder, id)
			}
			for name, p := range values {
				if !validChance(p) {
					return fmt.Errorf("passive %s %d %s = %d", holder, itemID, name, p)
				}
			}
			byID[itemID] = values
		}
		d.passives[holder] = byID
	}
	d.xun = map[int]bool{}
	for _, kart := range d.XunKarts {
		if kart <= 0 || d.xun[kart] {
			return fmt.Errorf("xun kart %d invalid", kart)
		}
		d.xun[kart] = true
	}
	keys := map[string]bool{}
	for _, title := range d.Titles {
		if title.Key == "" || keys[title.Key] {
			return fmt.Errorf("title %q invalid", title.Key)
		}
		keys[title.Key] = true
		for _, idx := range title.Items {
			if !d.raceItem(idx) {
				return fmt.Errorf("title %s counts unknown item %d", title.Key, idx)
			}
		}
		conditions := 0
		for _, set := range []bool{title.Fail != nil, title.Use > 0, title.Custom > 0} {
			if set {
				conditions++
			}
		}
		if conditions != 1 || (title.Use > 0) != (len(title.Items) > 0) {
			return fmt.Errorf("title %s needs exactly one condition", title.Key)
		}
	}
	for _, key := range TitleKeys {
		if !keys[key] {
			return fmt.Errorf("title %s missing", key)
		}
	}
	return nil
}

// requiredStates are the states the server timelines read (besides the
// eta and lock states of the rules, checked by indexPhase3).
var requiredStates = map[int][]string{
	WaterFly:      {"Use"},
	Rocket:        {"Use"},
	UFO:           {"Use", "Affect", "HeadBandAffect", "BonusAffect"},
	SlotLock:      {"Use", "Affect", "Postaffect"},
	Scanning:      {"Use", "Affect"},
	Angel:         {"Use", "Affect"},
	Shield:        {"Use"},
	TimeBomb:      {"Use"},
	Barricade:     {"StateUse"},
	WaterBomb:     {"Use"},
	Banana:        {"Use", "Set"},
	Devil:         {"Use", "Preaffect", "Affect"},
	Thunderbolt:   {"Use", "Warning", "Preaffect", "Affect"},
	Cloud:         {"Use", "Set"},
	EMP:           {"Use", "Affect"},
	Magnet:        {"Use"},
	GoldShield:    {"Use", "Affect"},
	ProtectShield: {"Use", "Affect"},
}

// Table returns the probability table of kind (TableIndividual, TableTeam,
// TableIndiChanger, TableTeamChanger).
func (d *Data) Table(kind string) *Table { return d.Tables[kind] }

// Item returns a table item.
func (d *Data) Item(idx int) (Item, bool) {
	item, ok := d.items[idx]
	return item, ok
}

// Cap returns how many times a racer can get idx in one race; ok is false
// for an item the restriction does not limit.
func (d *Data) Cap(idx int) (allowCount int, ok bool) {
	allowCount, ok = d.caps[idx]
	return allowCount, ok
}

// Track returns an item room track.
func (d *Data) Track(id string) (Track, bool) {
	track, ok := d.tracks[id]
	return track, ok
}

// Pool returns the tracks of a random-track code (nil for a code item rooms
// do not accept).
func (d *Data) Pool(code int) []string { return d.pools[code] }

// Passive returns the item-race chance (percent, 0 when none) of a passive
// attribute of the item itemID held as holder (HolderKart, …).
func (d *Data) Passive(holder string, itemID int, attribute string) int {
	return d.passives[holder][itemID][attribute]
}

// XunKart reports whether kart is a 迅 item kart (it starts holding an item).
func (d *Data) XunKart(kart int) bool { return d.xun[kart] }

var loadDefault = sync.OnceValues(func() (*Data, error) { return Parse(embedded) })

// Default returns the embedded data, parsed once.
func Default() (*Data, error) { return loadDefault() }
